### ISSUE TITLE
ElmerGUI Model - Setup Dialog size

### ISSUE THREAD

**Issue by grayhaired** [ElmerCSC/elmerfem#103]
In Ubuntu, When I open Model -> Setup dialog of ElmerGUI, first I can see the "apply" button. When I close it, and again open the Setup dialog, I CAN NOT see 'apply' button at all, and I'm stuck without being able to "apply". 

I request to you please reduce the "height" of the window, and in fact, "free text" field is given unnecessary space and using valuable space in the dialog. You can reduce that free text field height, and make "apply" visible. 

It's also not possible to resize. I also request you reduce height of any other such windows, which creates problems for users who're heavily dependent on GUI. 
![elmer](https://user-images.githubusercontent.com/26151427/27984508-88b412c8-63f5-11e7-8098-8569d0477b76.png)

Thank you very much.

**Comment by raback** [comment]
Hi, whereas I agree this would be nice there is a work-around. 

You can drag any dialog with the mouse when keeping "Alt" pressed. This way you can access the whole dialog. 

Due to this feature I'm afraid that this is low in priority.

**Comment by grayhaired** [comment]
Thanks for the reply and solution. I really appreciate info on work-around. I could move the dialogue and access all buttons. 
But I still request to reduce the window height/free text field height for the simple reason that there will be many users who will not know the workaround, and when they're starting to use Elmer, this bug can demotivate eager users. In my case, just because of this one bug, I found it very difficult to use it. 

Request you to do it early.  Thank you!!

**Comment by raback** [comment]
This has been addressed by saeki.
