### ISSUE TITLE
circuits_harmonic_stranded_homogenization test fails

### ISSUE THREAD

**Issue by juhanikataja** [ElmerCSC/elmerfem#106]
* `WARNING:: CompareToReferenceSolution: Solver 7 FAILED:  Norm = 4.19436489E-11  RefNorm = 1.63166208E-09`
* electromagnetic field energy becomes  2.2158627291992691E+082'

**Comment by raback** [comment]
I think somebody has fixed all the tests since none of them fail now ;-)
