### ISSUE TITLE
add topic on github 

### ISSUE THREAD

**Issue by HoWilgh** [ElmerCSC/elmerfem#110]
Please add topics like "fem" or "multiphysics" on github like the are used for goma https://github.com/goma/goma or Kratos https://github.com/KratosMultiphysics/Kratos . 

Thanks, 
Howil

**Comment by raback** [comment]
Howil, could you ellaborate the idea. GitHub includes the code with some ~50 examples of PDEs. Also there are hundreds of consistency tests for various features providing a possible starting point.

**Comment by raback** [comment]
Ok, I think I got it. I bunch of keywords were added to the elmerfem repository. Thank you for the useful suggestion!
