### ISSUE TITLE
build elmerfem using Qt5

### ISSUE THREAD

**Issue by Poofee** [ElmerCSC/elmerfem#117]
How to build the project using Qt5? I tried to add WITH_QT5 macro, but it failed. I can compiled it using Qt4 without problems. However, when I used Qt5 kit, a lot of errors occur.
<img width="401" alt="snipaste_20171010_110911" src="https://user-images.githubusercontent.com/10039950/31367687-94b5759e-adab-11e7-89c3-6ed0b8a2667a.png">
I learned Elmerfem can be built with Qt5, so could anyone give me a hand?

**Comment by Foadsf** [comment]
As discussed on this [Reddit comment](https://www.reddit.com/r/osx/comments/8xuhs1/how_to_compile_elmer_fem_on_macos_with_openmpi/e276082?utm_source=share&utm_medium=web2x) and also [this issue](https://github.com/ElmerCSC/homebrew-elmerfem/issues/6), it seems that there are some halfbaked efforts towards porting the GUIs to Qt5. 

The important thing at the moment is that the software compiles with Qt4 first, which I can consider as a bug, and then porting to Qt5 is an enhancement.

**Comment by Foadsf** [comment]
Apparently, on [this FUNET fttp](http://www.nic.funet.fi/pub/sci/physics/elmer/bin/windows-test/ElmerFEM-gui_mpi-2020-02-27/) folder, there are attempts to upgrade to Qt5. haven't tested them though yet.

**Comment by Gary719** [comment]
To call porting to Qt5 an enhancement ignores the fact that Debian and Ubuntu no longer have Qt4 available. See https://widk.debian.org/Qt4Removal. With Buster (Debian 10) and all of its derivatives Elmer will no longer compile. At this point, I can not get a working copy of Elmer that meets my needs. Porting to Qt5 needs to be done **asap**. It seems, at present, that Elmer is only useable on Windoze. FreeCAD now uses the AppImage method of installation but I don't think this would work with Elmer. Elmer has too many different possible setups. Although, a series of AppImages with different content could be quick, temporary fix for the problem.
Gary719

**Comment by Poofee** [comment]
I have fixed this problem. I downloaded mingw qt5 , and after set correct OpenGL path, I can rebuild it sucessflully.

**Comment by Sudhanshu-Dubey14** [comment]
I had successfully compiled Elmer on my Arch Linux with Qt5. But now I need ElmerGUI and when trying to rebuild using the command given in README:

`cmake .. -DWITH_OpenMP:BOOLEAN=TRUE -DWITH_MPI:BOOLEAN=TRUE -DWITH_ELMERGUI:BOOLEAN=TRUE`

I get the error:

```
CMake Error at /usr/share/cmake-3.18/Modules/FindQt4.cmake:1314 (message):
  Found unsuitable Qt version "5.15.0" from /usr/bin/qmake, this code
  requires Qt 4.x
Call Stack (most recent call first):
  ElmerGUI/CMakeLists.txt:37 (FIND_PACKAGE)
```

So what should I do to get the ElmerGUI?
I don't want to install Qt4 as I already have Qt5.

**Comment by amiurunkj** [comment]
> :
> 
> ```
> CMake Error at /usr/share/cmake-3.18/Modules/FindQt4.cmake:1314 (message):
>   Found unsuitable Qt version "5.15.0" from /usr/bin/qmake, this code
>   requires Qt 4.x
> Call Stack (most recent call first):
> ```

Try -DWITH_QT5:BOOLEAN=TRUE

**Comment by kcraftcode** [comment]
`cmake .. -DWITH_OpenMP:BOOLEAN=TRUE -DWITH_MPI:BOOLEAN=TRUE -DWITH_ELMERGUI:BOOLEAN=TRUE -DWITH_QT5=TRUE`
`export PATH=/path/to/qt5/bin:$PATH`
`cmake .. -DOpenGL_GL_PREFERENCE=GLVND -DOpenGL_INCLUDE_DIR=/path/to/opengl/include`
`make
make install
`
If you still encounter compatibility issues, double-check any recent documentation or community discussions, as ongoing changes in dependencies might require different flags or further updates to the CMake scripts.
