### ISSUE TITLE
wrong pointers in //fem/src/ListMatrix.F90

### ISSUE THREAD

**Issue by Jm56Z** [ElmerCSC/elmerfem#148]
I'm on ArchLinux.

After cloning the repository and cmake as explained here : https://www.csc.fi/web/elmer/sources-and-compilation
I run ```# make install```, and at 58% , when ```[ 58%] Building Fortran object fem/src/CMakeFiles/elmersolver.dir/ListMatrix.F90.o```
I get four errors with ```contiguous pointers affected from non-contiguous pointers``` :
```
A % Values => Values //line 224:18
A % Rows => Rows //line 154:16
A % Diag => Diag //line 155:16
A % Cols => Cols //line 156:16
```
exiting with :
```
make[2]: *** [fem/src/CMakeFiles/elmersolver.dir/build.make:310: fem/src/CMakeFiles/elmersolver.dir/ListMatrix.F90.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:644: fem/src/CMakeFiles/elmersolver.dir/all] Error 2
make: *** [Makefile:163: all] Error 2
```

**Comment by raback** [comment]
Just fixed these on devel. Thanx for reporting! Seems to be compiler dependent issue.
