### ISSUE TITLE
elmersolver_link target does not have a dependency to Solver_TGT

### ISSUE THREAD

**Issue by mbycklin** [ElmerCSC/elmerfem#155]
https://github.com/ElmerCSC/elmerfem/blob/f16c4c2640f834d9c80ff80ac164bcc32085957e/fem/src/CMakeLists.txt#L297

The new target does not have a dependency to `Solver_TGT`, which breaks parallel builds (commit ae425b3e52c7bac728cb974bc06635360bbcde93). 

Adding `ADD_DEPENDENCIES(elmersolver_link Solver_TGT)` after the problematic line seemed to generate the dependency correctly (with very limited testing).

**Comment by juhanikataja** [comment]
`ADD_DEPENDENCIES` looks to be the exactly right command, according to cmake manual. Fixed in  40a1744.
