### ISSUE TITLE
ElmerGrid: Handle new GMSH File Format v4.0

### ISSUE THREAD

**Issue by martinbaun** [ElmerCSC/elmerfem#160]
GMSH version 4 is released. Therein the new mesh format 4.0 is used. Documentation of the new file format:
[http://gmsh.info/doc/texinfo/gmsh.html#MSH-file-format-_0028version-4_0029](http://gmsh.info/doc/texinfo/gmsh.html#MSH-file-format-_0028version-4_0029)

 It would be great if ElmerGrid can handle this in future. I`ve attached an example of the new file-format.

[example_mesh_4.0.zip](https://github.com/ElmerCSC/elmerfem/files/2373790/example_mesh_4.0.zip)

**Comment by raback** [comment]
There is now a working version of the v4 import on "devel" branch. Haven't tested too extensively though. Maybe you can try it to your mesh files.

**Comment by martinbaun** [comment]
I've tried it with a simple 3D geometry and compared the mesh versions 2.2 and 4.0. I used the nightly build of gmsh (2018-10-24) and the elmer code from today (2018-10-24).
Converting with
`ElmerGrid 14 2 mesh_2.2.msh --autoclean`
`ElmerGrid 14 2 mesh_4.0.msh --autoclean`

There some issues with the new file-format when converting it with ElmerGrid:
1) There should be about 6015 elements. In mesh_4/mesh.elements all elements with number>1008 have no nodes
2) In mesh_4/mesh.names are incomplete (maybe because of the missing elements)

[01_gmsh_fileformat_4.0.zip](https://github.com/ElmerCSC/elmerfem/files/2510716/01_gmsh_fileformat_4.0.zip)

**Comment by raback** [comment]
Thanx for testing! Indeed, there was some bugs & unsufficient treatment of physical entities. Just committed a new version which treats this case properly. Note that when using physical groups (instead of "save all" in old gmsh) there should be no need for autoclean since only given groups are saved. Personally I've liked the "save all" flag in gmsh at least when you plan clicking the BCs in ElmerGUI. Don't know if the "save all" option is available in Gmsh4 format?

**Comment by martinbaun** [comment]
Great, the simple example works. So I continued with a more complex model. With this I have the problem, that some physical entities are not saved in the mesh.names file again. 
I confess that I don't know exactly, what's the effect of "--autoclean". For my simulation I always name all parts in GMSH because I need it for full automation.

[complex_example.zip](https://github.com/ElmerCSC/elmerfem/files/2517918/complex_example.zip)

**Comment by raback** [comment]
I did some updates. It seems that the "$Entities" lines are sometimes very long. I just pick up the 1st physical label but there were at worst tens of them in your file?

**Comment by martinbaun** [comment]
Can`t say something about the new gmsh file format. But your modifications results in a correct mesh model. I`ve done a simulation and the results are the same as with the old gmsh format. 

Further I´ve expanded the example to a more complex one. There are some new physical volumes in it. After converting it with the new ElmerGrid version the physical volume "PM4" is missing. Could you check that?

[complex2.zip](https://github.com/ElmerCSC/elmerfem/files/2530290/complex2.zip)

**Comment by raback** [comment]
Little busy. If the problem was the same as last time you could try to increase LONGLINESIZE in femtypes.h from its current value 3000. Particularly if the complaint is as last time this would suggest that the buffer is still not long enough to handle one line in gmsh file. Pretty long lines...

**Comment by martinbaun** [comment]
You're right. It's a problem with the line length. The longest line in my file has 3366 characters. After increasing "LONGLINESIZE" ElmerGrid converts the mesh correct. But I`m not sure if this solves the problems in the future. As I understand the $Entities section contains all parent entities for each entity. For a surface there are all curves listed which are part of the surface. (there are many in my model) So the line length grows with the number of "parent-entities" and depend how the user model his geometry. So there is no fix border which limits the line length.
Is it possible to detect the line length automatically in ElmerGrid?

**Comment by raback** [comment]
My hope was to make just minimal update. The logic of the parsers of ElmerGrid has been to read in one line on the buffer and the analyze that more closely. The principle has worked well for all formats so far. Having this long lines sort of breaks the logic. I can try to overcome this but it is not on the top of  the to-do list.

**Comment by raback** [comment]
Ok, I added a check for newline character so that we fill the buffer until one found. The values are really not used for anything but the mesh is succesfully read after the fix. Will close the issue.

**Comment by jleman** [comment]
I am trying to convert a simple cube mesh (gmsh 4.5.1) into Elmer .mesh format using the ElmerGrid version that comes with the elmerfem-mpi-8.4_Windows-AMD64.exe distirubtion on github (2018-12-20 11:56  120M).  Attached is the .msh file and the output result from the ElmerGrid command.  No output file or folder was generated.  Is this perhaps related to the above thread?  Thanks.

[gmsh msh file and ElmerGrid command line output.zip](https://github.com/ElmerCSC/elmerfem/files/4016740/gmsh.msh.file.and.ElmerGrid.command.line.output.zip)
