### ISSUE TITLE
Elmer compiled with Trilinos in Fedora Linux: rpath_change

### ISSUE THREAD

**Issue by espinozahg** [ElmerCSC/elmerfem#162]
I can compile Elmer with Trilinos in Fedora Linux
cmake works well
make works well
make install works well
ldd ./fem/src/ElmerSolver_mpi ; # finds all libraries
ldd ../bin/ElmerSolver ; # it cannot find Trilinos Libraries.
I guess the problem comes from the file ./fem/src/cmake_install.cmake  Specifically Line 50 which reads

file(RPATH_CHANGE
         FILE "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/bin/ViewFactors"
         OLD_RPATH "/usr/lib64/openmpi/lib:/home/username/elmer-git-2018-10-12/build/fem/src:/home/username/elmer-git-2018-10-12/build/matc/src:/home/username/elmer-git-2018-10-12/build/fhutiter/src:/home/username/elmer-git-2018-10-12/build/mathlibs/src/arpack:/home/username/elmer-git-2018-10-12/build/mathlibs/src/parpack:/home/username/trilinos-12.12.1/lib:"
         NEW_RPATH "$ORIGIN/../lib/elmersolver")

I understand you do that change so the Elmer Libraries the Executable wants are in ./lib/elmersolver but the Trilinos library is deleted in the process.

the cmake command I am using is:
cmake -DWITH_ELMERGUI:BOOL=TRUE -DWITH_OpenMP:BOOL=FALSE -DWITH_MPI:BOOL=TRUE -DWITH_VTK:BOOL=TRUE -DWITH_Hypre:BOOL=TRUE -DHypre_LIBRARIES:FILEPATH=/usr/lib64/openmpi/lib/libHYPRE.so -DHypre_INCLUDE_DIR:PATH=/usr/include/openmpi-x86_64/hypre -DWITH_Mumps:BOOL=TRUE -DMumps_INCLUDE_DIR:PATH=/usr/include/openmpi-x86_64 -DSCALAPACK_LIBRARIES:FILEPATH=/usr/lib64/openmpi/lib/libscalapack.so -DMUMPS_COMMON_LIB:FILEPATH=/usr/lib64/openmpi/lib/libmumps_common.so -DMUMPS_D_LIB:FILEPATH=/usr/lib64/openmpi/lib/libdmumps.so -DMUMPS_PORD_LIB:FILEPATH=/usr/lib64/openmpi/lib/libpord.so -DWITH_OCC:BOOL=TRUE -DWITH_PARAVIEW:BOOL=TRUE -DWITH_QWT:BOOL=TRUE -DWITH_MATC:BOOL=FALSE -DWITH_Trilinos:BOOL=TRUE -DCMAKE_Fortran_FLAGS:STRING="-march=native" -DCMAKE_C_FLAGS:STRING="-march=native" -DCMAKE_CXX_FLAGS:STRING="-march=native" -DMPI_Fortran_COMPILE_FLAGS:STRING="-march=native" -DMPI_C_COMPILE_FLAGS:STRING="-march=native" -DMPI_CXX_COMPILE_FLAGS:STRING="-march=native" -DCMAKE_PREFIX_PATH="/home/username/parmetis-4.0.3;/home/username/trilinos-12.12.1" -DCMAKE_INSTALL_PREFIX=.. ../elmer-git-2018-10-12

the version of Elmer I am using is the devel branch from 12/october/2018, something around
https://github.com/ElmerCSC/elmerfem/tree/3d8ad28a63c5fae6d48f52e128705c2c494fa1a4

**Comment by espinozahg** [comment]
Additionally, I see some repeated code in file ./fem/src/cmake_install.cmake in line 103 to 121  and line 143 to 161.

**Comment by joeatodd** [comment]
Thanks for the report. Have you encountered this error with previous version of the code?

**Comment by espinozahg** [comment]
I tried to compile Elmer 8.3 (last release version) but the compiler was
giving errors so I could not even compile the code. Therefore, I could not
test the linking process or chech the executable with ldd. That is why I
turned to the devel version which compiles, linnks but has that small
problem at then end with rpath.

**Comment by joeatodd** [comment]
I made some changes to the RPATH handling in the past month or so, so I am interested to see if these are responsible. Could you possibly try checking out this commit: 7c9a36bce73f786b50f1a2e692a769b8436664c1
and see if the same problem occurs.

As a side note, a potential work around is to add your libtrilinos location to LD_LIBRARY_PATH.

**Comment by espinozahg** [comment]
I tested the commit you told me and it configures well with cmake, it
compiles and installs.
Doing ldd ./fem/src/ElmerSolver_mpi ; finds the trilinos libraries.
Doing ldd ../bin/ElmerSolver_mpi ; does not find the trilinos libraries (as
before)

Using LD_LIBRARY_PATH will probably find the libraries but that is not the
recommended method. I think rpath is the recommended method.

**Comment by joeatodd** [comment]
OK, so this is not a new problem. I will pass it on to someone who knows more about cmake - thanks for the report.

**Comment by tehnick** [comment]
> Using LD_LIBRARY_PATH will probably find the libraries but that is not the recommended method. I think rpath is the recommended method.

As far as I remember it is quite opposite:
https://fedoraproject.org/wiki/RPath_Packaging_Draft#Beware_of_Rpath
https://fedoraproject.org/wiki/Packaging:Guidelines#Beware_of_Rpath
https://wiki.debian.org/RpathIssue

But for personal usage (for manually built programs) RPATH is fine.

**Comment by espinozahg** [comment]
As far as I understand rpath and runpath and LD_LIBRARY_PATH are not
recommended/needed for system packages (i. e. in fedora a package installed
using sudo dnf install pkg) because all dependencies will be installed or
satisfied using other system packages which are installed in standard
locations. Therefore ld will find the libraries in those standard locations.
This case is different because it is a user compiled and linked application
against a user compiled library (trilinos is not available as a fedora
package). I mean an app which is not installed doing sudo dnf install pkg.
In this case I trilinos is in a non-standard location. Possibly it is a
trilinos version which suits Elmer.

The third scenario: trilinos and all libraries on which elmer depends are
available as systems packages, therefore there is no need of rpath
LD_LIBRARY_PATH or runpath. But this is not the case either because elmer
depends on some elmer libraries which are correctly set an located using
rpath.

Some interesting links about rpath and related:
https://www.hpc.dtu.dk/?page_id=1180
https://amir.rachum.com/amp/blog/2016/09/17/shared-libraries.html
https://gms.tf/ld_library_path-considered-harmful.html

**Comment by juhanikataja** [comment]
Hi,

First of all, thanks for bringing this up. But, I think this is not an Elmer related issue.

Installing a shared library (Trilinos in this case) to a nonstandard location forces user to tell linker somehow where to find the library. That can be done using the `LD_LIBRARY_PATH` environment variable or `RPATH`. In Elmer, `RPATH` is used to find shared libraries compiled alongside the Elmer solver binary (such as libelmersolver.so, libarpack.so, libfhuti.so, etc.).

I strongly discourage placing third party library paths in `RPATH` in Elmer. Instead `LD_LIBRARY_PATH` must be utilized.

ps. I don't think `LD_LIBRARY_PATH` is not that bad if wielded properly. For example, [lmod](https://www.tacc.utexas.edu/research-development/tacc-projects/lmod) will help keep `LD_LIBRARY_PATH` clean.
