### ISSUE TITLE
Warning from CMake about SET CMP0022 OLD

### ISSUE THREAD

**Issue by Russell-Jones-OxPhys** [ElmerCSC/elmerfem#164]
Hi, I get a warning from CMake 3.10.2 on Ubuntu 18.04 that setting OLD is deprecated and won't be supported in future.

```
 CMake Deprecation Warning at CMakeLists.txt:51 (CMAKE_POLICY):
   The OLD behavior for policy CMP0022 will be removed from a future version
   of CMake.

   The cmake-policies(7) manual explains that the OLD behaviors of all
   policies are deprecated and that a policy should be set to OLD only under
   specific short-term circumstances.  Projects should be ported to the NEW
   behavior and not rely on setting a policy to OLD.
```

**Comment by Foadsf** [comment]
Dear @raback , the CMake scripts are utterly outdated. It would be great if we could already start restructuring and updating them according to modern CMake.

**Comment by Foadsf** [comment]
commenting the lines:

~~~
# if("${CMAKE_VERSION}" VERSION_GREATER 2.8.12)
#   CMAKE_POLICY(SET CMP0022 OLD)
# ENDIF()
~~~

out had zero effect on the compilation process on the macOS. ¯\\\_(ツ)\_/¯

according to [CMake documentation](https://cmake.org/cmake/help/v3.8/policy/CMP0022.html), `CMP0022` should only concern the usage of some functions including `INTERFACE_LINK_LIBRARIES` which we don't have in the codebase at all! I will push to the [wip/mac](https://github.com/ElmerCSC/elmerfem/tree/wip/mac) branch. I would appreciate it if you could test on other OSes (i.e., Windows, Linux, ...)

**Comment by mmuetzel** [comment]
Afaict, that policy isn't set any more since more than 4 years.

This issue can probably be closed.
