### ISSUE TITLE
Add repology badge to README 

### ISSUE THREAD

**Issue by luzpaz** [ElmerCSC/elmerfem#165]
<table>
  <tr>
    <th>elmerfem</th>
    <th>elmer-doc</th>
  </tr>
  <tr>
    <td valign="top"><a href="https://repology.org/metapackage/elmerfem/versions">
    <img src="https://repology.org/badge/vertical-allrepos/elmerfem.svg" alt="Packaging status"></a>
    </td>
    <td valign="top"><a href="https://repology.org/metapackage/elmer-doc/versions">
    <img src="https://repology.org/badge/vertical-allrepos/elmer-doc.svg" alt="Packaging status"></a>
    </td>
  </tr>
</table>

Or the badge could be smaller:

<a href="https://repology.org/project/elmerfem/versions">
    <img src="https://repology.org/badge/tiny-repos/elmerfem.svg" alt="Packaging status"></a
<a href="https://repology.org/project/elmer-doc/versions">
    <img src="https://repology.org/badge/tiny-repos/elmer-doc.svg" alt="Packaging status">
</a>

**Comment by raback** [comment]
This has been added by Foad!
