### ISSUE TITLE
Elmer not packaged for Ubuntu 18.10

### ISSUE THREAD

**Issue by rjsummers** [ElmerCSC/elmerfem#168]
I get the following error after adding the Elmer PPA:

```
Err:11 http://ppa.launchpad.net/elmer-csc-ubuntu/elmer-csc-ppa/ubuntu cosmic Release
  404  Not Found [IP: 91.189.95.83 80]
Reading package lists... Done                      
E: The repository 'http://ppa.launchpad.net/elmer-csc-ubuntu/elmer-csc-ppa/ubuntu cosmic Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

It looks like Elmer hasn't been packaged for 18.10 yet.

Thanks!

**Comment by tayebzaidi** [comment]
I can corroborate this with Ubuntu 19.04 as well: 
`The repository 'http://ppa.launchpad.net/elmer-csc-ubuntu/elmer-csc-ppa/ubuntu disco Release' does not have a Release file.`

**Comment by tzwinger** [comment]
I close that seemingly neglected issue, pointing out that both versions are now available on launchpad
