### ISSUE TITLE
elmerfem 8.3.20170524 - build error 

### ISSUE THREAD

**Issue by pgiffuni** [ElmerCSC/elmerfem#172]
From FreeBSD's pkg-builders:
...
cd /wrkdirs/usr/ports/cad/elmerfem/work/.build/fem/src &&
/usr/local/bin/gfortran8 -DCONTIG=,CONTIGUOUS -DHAVE_EXECUTECOMMANDLINE
-DUSE_ARPACK -DUSE_ISO_C_BINDINGS -Delmersolver_EXPORTS -I/usr/local/include
-I/wrkdirs/usr/ports/cad/elmerfem/work/.build
-I/wrkdirs/usr/ports/cad/elmerfem/work/.build/fem/src
-I/wrkdirs/usr/ports/cad/elmerfem/work/elmerfem-release-8.3/fhutiter/src
-I/wrkdirs/usr/ports/cad/elmerfem/work/.build/fem/src/binio
-I/wrkdirs/usr/ports/cad/elmerfem/work/.build/fhutiter/src  -O
-Wl,-rpath=/usr/local/lib/gcc8 -fPIC -O3 -DNDEBUG -O3 -J../../fmodules -fPIC  
-c
/wrkdirs/usr/ports/cad/elmerfem/work/elmerfem-release-8.3/fem/src/CRSMatrix.F90
-o CMakeFiles/elmersolver.dir/CRSMatrix.F90.o
/wrkdirs/usr/ports/cad/elmerfem/work/elmerfem-release-8.3/fem/src/CRSMatrix.F90:3681:24:

       A % ILUCols    => ILUCols
                        1
Error: Assignment to contiguous pointer from non-contiguous target at (1)

**Comment by luzpaz** [comment]
:point_up:

**Comment by juharu** [comment]
I'd try the fresh "release" branch.

**Comment by raback** [comment]
Outdated
