### ISSUE TITLE
Elmer Opens 3d .msh file genetrated in Gmsh as 2D Mesh Image

### ISSUE THREAD

**Issue by machinedesign09** [ElmerCSC/elmerfem#181]
when i open .msh file generated from Gmsh in Elmer...It Opens in 2D Mesh Image. Z axis data gone..what is the reason, kindly help

**Comment by raback** [comment]
I'm little late here but seeing the .msh file woudl help. There can be real problem with the read-in but also problems with the GPUs have resulted to wrong view. If you're still reading you would provide the .msh file for audit.

**Comment by raback** [comment]
I will close this as there has been fixes and no non-working example file is available.
