### ISSUE TITLE
Segmentation fault opening binary stl

### ISSUE THREAD

**Issue by Fellypao** [ElmerCSC/elmerfem#182]
ElmerGUI crashes when one try to open a binary stl mesh file.

Error message from terminal:

Selected nglib for stl-format
Initializing nglib
Start meshing...
Segmentation fault

The software should not crash even if binary stl import is not supported.
A binary stl sample is attached. It was generated using FreeCAD. Gmsh is able to import it without problems.
Best regards.
[02-core.stl.tar.gz](https://github.com/ElmerCSC/elmerfem/files/3451900/02-core.stl.tar.gz)

**Comment by raback** [comment]
Here we rely (perhaps on too old) external libraries. Of course you're rigtht that the code should not crash even in this case.
