### ISSUE TITLE
Basis Function Problem

### ISSUE THREAD

**Issue by HaoWangCyy** [ElmerCSC/elmerfem#184]
When I read a paragraph of the code you wrote, it read as follows
IF (SecondOrder) THEN
           ! DOFs is the number of H(curl)-conforming basis functions: 
           DOFs = 8
           IF (n == 6) THEN
             ! Here the element of the background mesh is of type 306.
             ! The Lagrange interpolation basis on the p-approximation reference element:
             Basis(1) = (3.0d0*u**2 + v*(-Sqrt(3.0d0) + v) + u*(-3.0d0 + 2.0d0*Sqrt(3.0d0)*v))/6.0d0
             dLBasisdx(1,1) = -0.5d0 + u + v/Sqrt(3.0d0)
             dLBasisdx(1,2) = (-Sqrt(3.0d0) + 2.0d0*Sqrt(3.0d0)*u + 2.0d0*v)/6.0d0
             Basis(2) = (3.0d0*u**2 + v*(-Sqrt(3.0d0) + v) + u*(3.0d0 - 2.0d0*Sqrt(3.0d0)*v))/6.0d0
             dLBasisdx(2,1) = 0.5d0 + u - v/Sqrt(3.d0)
             dLBasisdx(2,2) = (-Sqrt(3.0d0) - 2.0d0*Sqrt(3.0d0)*u + 2.0d0*v)/6.0d0
             Basis(3) = (v*(-Sqrt(3.0d0) + 2.0d0*v))/3.0d0
             dLBasisdx(3,1) = 0.0d0
             dLBasisdx(3,2) =  -(1.0d0/Sqrt(3.0d0)) + (4.0d0*v)/3.0d0
             Basis(4) = (3.0d0 - 3.0d0*u**2 - 2.0d0*Sqrt(3.0d0)*v + v**2)/3.0d0
             dLBasisdx(4,1) = -2.0d0*u
             dLBasisdx(4,2) = (-2.0d0*(Sqrt(3.0d0) - v))/3.0d0
             Basis(5) = (2.0d0*(Sqrt(3.0d0) + Sqrt(3.0d0)*u - v)*v)/3.0d0
             dLBasisdx(5,1) =  (2.0d0*v)/Sqrt(3.0d0)
             dLBasisdx(5,2) = (2.0d0*(Sqrt(3.0d0) + Sqrt(3.0d0)*u - 2.0d0*v))/3.0d0
             Basis(6) = (-2.0d0*v*(-Sqrt(3.0d0) + Sqrt(3.0d0)*u + v))/3.0d0           
             dLBasisdx(6,1) = (-2.0d0*v)/Sqrt(3.0d0)
             dLBasisdx(6,2) = (-2.0d0*(-Sqrt(3.0d0) + Sqrt(3.0d0)*u + 2.0d0*v))/3.0d0
           ELSE
             ! Here the element of the background mesh is of type 303:
             DO q=1,3
               Basis(q) = TriangleNodalPBasis(q, u, v)
               dLBasisdx(q,1:2) = dTriangleNodalPBasis(q, u, v) 
             END DO
           END IF
         ELSE
           DO q=1,n
             Basis(q) = TriangleNodalPBasis(q, u, v)
             dLBasisdx(q,1:2) = dTriangleNodalPBasis(q, u, v) 
           END DO
           IF (Create2ndKindBasis) THEN
             DOFs = 6
           ELSE
             DOFs = 3
           END IF
         END IF
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%First question : 
Should there be eight basis functions about second order H(curl)-conforming basis functions in 2 two-dimensional on a triangular mesh？Why you just give six basis functions？
Secon question :
mesh is of type 306，303，etc，Where can I find or see the mesh?
I hope I can get your reply and help！
Best wishes！

**Comment by mmalinen** [comment]
As the comments of the code explain, the variable Basis gives basis functions for the standard H^1-regular approximation:

`       REAL(KIND=dp) :: Basis(:)                 !< H1-conforming basis functions evaluated at (u,v,w)`

The variable EdgeBasis is used to return a curl-conforming basis:

`       REAL(KIND=dp) :: EdgeBasis(:,:)           !< The basis functions b spanning the reference element space`

In this case the count of curl-conforming basis functions is indeed 8. 

The background mesh (which may for example consist of 3-node elements, the Elmer element code 303) is defined using four separate files mesh.header, mesh.nodes, mesh.elements and mesh.boundary; for additional information see the Appendices A of F of the ElmerSolver Manual

http://www.nic.funet.fi/pub/sci/physics/elmer/doc/ElmerSolverManual.pdf

**Comment by HaoWangCyy** [comment]
Thank you very much for your reply and answer.
I know now the linear (303) and quadratic (306) triangular elements which you provided the website.
In fact，I just want to know concrete second baisis of edge element for the linear (303) triangular elements in 2D, I know when I see your document，the count of curl-conforming basis functions is indeed 8. Maybe I'm not familiar with your package, can you spare your time and help me write out the concrete form of the base function of this 8？
I would like to express my most sincere thanks to you.


--

Best regards,
Hao Wang (王昊)

School of Mathematics and
Computational Science,
Xiangtan University,
Xiangtan, 411105.
wanghao106031@126.com;

283105210@qq.com;
(Tel:) (+86)18873220835
 

At 2019-08-19 15:15:05, "mmalinen" <notifications@github.com> wrote:


As the comments of the code explain, the variable Basis gives basis functions for the standard H^1-regular approximation:

REAL(KIND=dp) :: Basis(:) !< H1-conforming basis functions evaluated at (u,v,w)

The variable EdgeBasis is used to return a curl-conforming basis:

REAL(KIND=dp) :: EdgeBasis(:,:) !< The basis functions b spanning the reference element space

In this case the count of curl-conforming basis functions is indeed 8.

The background mesh (which may for example consist of 3-node elements, the Elmer element code 303) is defined using four separate files mesh.header, mesh.nodes, mesh.elements and mesh.boundary; for additional information see the Appendices A of F of the ElmerSolver Manual

http://www.nic.funet.fi/pub/sci/physics/elmer/doc/ElmerSolverManual.pdf

**Comment by mmalinen** [comment]
The Elmer code gives explicit expressions for the curl-conforming basis functions as defined over the reference element. For triangles it should be possible to pick these by traversing ElementDescription.F90 as today from around the line 6020 onwards. The corresponding basis on a physical element is constructed algorithmically (via applying the Piola-like transformation) and is not thus explicit.

**Comment by HaoWangCyy** [comment]
Thank you very much for your reply and help. I will try to find them and verify them.
