### ISSUE TITLE
error #6691: A pointer dummy argument may only be argument associated with a pointer.   [ELEMENT]

### ISSUE THREAD

**Issue by hellogxp** [ElmerCSC/elmerfem#196]
Hi
When I tried to install Elmer/Ice use

cmake -C ../elmer-opts.cmake ../elmerfem -DWITH_ElmerIce:BOOL=TRUE -DWITH_MPI:BOOL=TRUE
make -j8 install

I got the error

error #6691: A pointer dummy argument may only be argument associated with a pointer.   [ELEMENT]
           CALL PickActiveFace(Mesh, Parent, Element, Face, ActiveFaceId)
---------------------------------------------^
compilation aborted for /lustre/home/d171/s1883636/elmerfem/fem/src/ElementDescription.F90 (code 1)
make[3]: *** [fem/src/CMakeFiles/elmersolver.dir/ElementDescription.F90.o] Error 1
make[2]: *** [fem/src/CMakeFiles/elmersolver.dir/ElementDescription.F90.o.provides] Error 2
make[1]: *** [fem/src/CMakeFiles/elmersolver.dir/all] Error 2
make: *** [all] Error 2

I google the solution and find this
https://software.intel.com/en-us/forums/intel-fortran-compiler/topic/506778

but I do not know is it a bug or I did not have the right way, tks

**Comment by raback** [comment]
This has been fixed.

**Comment by hellogxp** [comment]
Got it, thank you
