### ISSUE TITLE
Segmentation fault when importing unv with multiple boundaries

### ISSUE THREAD

**Issue by GMellar** [ElmerCSC/elmerfem#205]
I have created s simple box with salome and exported it to unv. The conversion with ElmerGrid to a mesh format was successful but loading this leads into segmentation fault of ElmerGUI. Without any surface groups everything works fine. I use debian 10 on x86_64 and the latest stable elmerfem version.

**Comment by raback** [comment]
This should have been fixed as ElmerGUI uses now same codebase as ElmerGrid.
