### ISSUE TITLE
NSIS Error when using the non-MPI installer from SourceForge

### ISSUE THREAD

**Issue by Foadsf** [ElmerCSC/elmerfem#211]
Downloading [this installer]([url](https://sourceforge.net/projects/elmerfem/files/WindowsBinaries/Win64Installer/elmerfem-nightly_Windows-AMD64.exe/download)) one gets the error message:

<pre>
<img src="https://user-images.githubusercontent.com/12762442/78828084-71fafd00-79e4-11ea-83bb-961f697e8f61.png" width="500">               
</pre>

<pre>
NSIS Error

Installer integrity check has failed. Common causes include 
incomplete download and damaged media. Contact the
installer's author to obtain a new copy.

More information at:
http://nsis.sf.net/NSIS_Error
</pre>

the [MPI version](https://sourceforge.net/projects/elmerfem/files/WindowsBinaries/Win64InstallerMPI/elmerfem-mpi-nightly_Windows-AMD64.exe/download) does not have this error and installs, though with some other errors.

**Comment by raback** [comment]
I think the current installers are not corrupt.
