### ISSUE TITLE
FindNN.cmake in elmerice/cmake/Modules/ looking for wrong nn header

### ISSUE THREAD

**Issue by orliac** [ElmerCSC/elmerfem#224]
```
# Try to find NN
FIND_PATH(NN_INCLUDE_DIR
  nan.h 
  HINTS 
  ${NNINCLUDE}
  )
```
Should be looking for nn.h

**Comment by chekki2mo** [comment]
Hi Etienne:
You are right , I am going to change this at the next pull. 
This is not blocking as long as you refer to the include directory. The header is not used in this solver.

Best
