### ISSUE TITLE
Error: Rank mismatch between actual argument at (1) and actual argument at (2) (scalar and rank-1)

### ISSUE THREAD

**Issue by Sudhanshu-Dubey14** [ElmerCSC/elmerfem#231]
I am trying to install elmerfem from this [AUR package](https://aur.archlinux.org/packages/elmerfem/) and facing this error during compilation:

    [  3%] Building Fortran object mathlibs/src/arpack/CMakeFiles/arpack.dir/cnaitr.f.o
    /home/sudhanshu/builds/elmerfem/src/elmerfem-release-8.4/mathlibs/src/arpack/cnaitr.f:666:35:
   
    383 |             call svout (logfil, 1, rnorm, ndigit,
           |                                   2 
     ......
    666 |             call svout (logfil, 2, rtemp, ndigit,
           |                                   1
    Error: Rank mismatch between actual argument at (1) and actual argument at (2) (scalar and rank-1)

I think it's just a case of a warning turning into an error, something like the work of -Werror flag, as another AUR package was successfully installed showing similar messages but as warning.
The thing is that I can't find the flag doing this. The flags shown during building are:

```
-- ------------------------------------------------
--   Fortran compiler:        /usr/bin/f95
--   Fortran flags:            -fopenmp -O2 -g -DNDEBUG
-- ------------------------------------------------
--   C compiler:              /usr/bin/cc
--   C flags:                 -D_FORTIFY_SOURCE=2 -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fopenmp -O2 -g -DNDEBUG
-- ------------------------------------------------
--   CXX compiler:            /usr/bin/c++
--   CXX flags:               -D_FORTIFY_SOURCE=2 -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fopenmp -O2 -g -DNDEBUG
-- ------------------------------------------------
--   MPI Fortran:             TRUE
--   MPI Fortran compiler:    /usr/bin/mpif90
--   MPI Fortran flags:       
--   MPI Fortran include dir: /usr/include;/usr/lib/openmpi
--   MPI Fortran libraries:   /usr/lib/openmpi/libmpi_usempif08.so;/usr/lib/openmpi/libmpi_usempi_ignore_tkr.so;/usr/lib/openmpi/libmpi_mpifh.so;/usr/lib/openmpi/libmpi.so
--   MPI Fortran link flags:   -Wl,-rpath  -Wl,/usr/lib/openmpi  -Wl,--enable-new-dtags
-- ------------------------------------------------
--   MPI C:             TRUE
--   MPI C compiler:    /usr/bin/mpicc
--   MPI C flags:       
--   MPI C include dir: /usr/include
--   MPI C libraries:   /usr/lib/openmpi/libmpi.so
--   MPI C flags:        -Wl,-rpath  -Wl,/usr/lib/openmpi  -Wl,--enable-new-dtags
-- ------------------------------------------------
```
Any help is really welcome.

**Comment by juharu** [comment]
Hi 

This error status of this age old fortran habit seems a feature of recent gfortran versions. 
Easiest workaround might be to add "-fallow-argument-mismatch" to "Fortran flags" ? 

More consistent fix - if gcc really will inisist on this in the future - might be to separate the options 
for old fortran 77 style source code and the more recent fortran source codes ... 

Br, ,Juha

**Comment by Sudhanshu-Dubey14** [comment]
Hi @juharu ,
Thanks for that flag!!
It helped me clear the original error by passing it off as a warning.
My gfortran version is `10.1.0` by the way.

But after that I got another error:

```
/home/sudhanshu/builds/elmerfem/src/elmerfem-release-8.4/fem/src/BandwidthOptimize.F90:91:0:

   91 |         IF ( PRESENT( InvInitialReorder ) ) j = InvInitialReorder(j)
      | 
Error: ‘invinitialreorder’ not specified in enclosing ‘parallel’
/home/sudhanshu/builds/elmerfem/src/elmerfem-release-8.4/fem/src/BandwidthOptimize.F90:92:0:

   92 |         DO WHILE( ASSOCIATED( CList ) )
      | 
Error: enclosing ‘parallel’
/home/sudhanshu/builds/elmerfem/src/elmerfem-release-8.4/fem/src/BandwidthOptimize.F90:95:0:

   95 |            IF ( .NOT. PRESENT( Reorder ) ) THEN
      | 
Error: ‘reorder’ not specified in enclosing ‘parallel’
/home/sudhanshu/builds/elmerfem/src/elmerfem-release-8.4/fem/src/BandwidthOptimize.F90:92:0:

   92 |         DO WHILE( ASSOCIATED( CList ) )
      | 
Error: enclosing ‘parallel’
make[2]: *** [fem/src/CMakeFiles/elmersolver.dir/build.make:369: fem/src/CMakeFiles/elmersolver.dir/BandwidthOptimize.F90.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:15410: fem/src/CMakeFiles/elmersolver.dir/all] Error 2
make: *** [Makefile:183: all] Error 2
```

Could you help me out with this one too, or should I open a new issue for this and close this one?

**Comment by juharu** [comment]
Hi 

Good that it worked! 

[ https://github.com/ElmerCSC/elmerfem/issues/226 | I think issue #226 "gfortran 10 openmp compile error ] " below addresses your next problem... ? 

Br, Juha

**Comment by Sudhanshu-Dubey14** [comment]
Since the original issue is resolved, I will go ahead and close it.
Thanks for helping me out.
