### ISSUE TITLE
install Paralution's plugin for Elmerfem

### ISSUE THREAD

**Issue by cTatu** [ElmerCSC/elmerfem#232]
Hello, I'm writing this here because I couldn't find any other support on the official website or forum. I will be very grateful if someone with a little more experience could, at least, guide me towards the right way.
I would want to use [Paralution's](https://www.paralution.com/) plug-in for Elmer in order to solve the simulations on the GPU. 

I successfully  compiled Paralution shared library with CUDA backend support (cuda 6.5).

Next I followed the instructions from paralution's [user manual](https://www.paralution.com/downloads/paralution-um.pdf#page=83&zoom=100,-55,511) in order to add the plug-in to Elmer and compile it (compile Elmer with the plugin). I used release version 8.0 of Elmer since that was the only version which had the required files listed on the instructions (`/fem/src/Makefile.in` and `/fem/src/Makefile.am`).

After making all the changes listed in the manual, I proceeded to compile Elmer using `cmake .. -DWITH_OpenMP:BOOLEAN=FALSE -DWITH_MPI:BOOLEAN=FALSE` since I only want to use the GPU solver which, in theory, will be provided by Paralution's plug-in.

NOTE: I skipped step number 6 because I didn't know how to do it.
> 6. Finally, you need to add the library dependencies of PARALUTION (-fopenmp, -lcudart, etc.  dependent on the backends you compiled PARALUTION with) to the Elmer Makefile .

But the compilation failed throwing this error:
```
libelmersolver.so: undefined reference to `paralutionsolve_'
collect2: error: ld returned 1 exit status
make[2]: *** [fem/src/ElmerSolver] Error 1
```
I guess the instructions from the user manual are also outdated but are all there is. It will be very nice if someone could help me with the error or has a better way to add the plug-in to Elmer.
Thank you in advance!

**Comment by raback** [comment]
I think the Paralution plugin instructions refer to GNU autotools build (Makefile.am is related to this). At the same time around 6-7 years ago when the code migrated from SourceForge to GitHub it was also changed to be compiled under cmake. Hence the guidance is obsolite. I think that the Makefile.* files remained for some time until they were removed as obsolite. So some cmake hack should invest some time to this.

**Comment by cTatu** [comment]
Thanks for your answer. 
That is just what I was afraid of. I would do that cmake hack if I knew how but, actually, I don't mind using those obsolete GNU autotools as long as I get it to work. 
Could you indicate me some hints, tutorials or instructions to compile Elmer using those old tools?
Thank you!

**Comment by raback** [comment]
The current codebase is not backward compatible with autotools. Probably the last version on sourceforge.net is the last one that uses it: https://sourceforge.net/p/elmerfem/code/HEAD/tree/trunk/ 
It's ~4600 commits behind current devel branch so there is really no sense to go back. 

Rather recently there has been trials to make amgx usable via Elmer. See branch, 
https://github.com/ElmerCSC/elmerfem/tree/amgx_interface

Maybe you could look if mimicing that work would get you further with paralution also.
