### ISSUE TITLE
Eigenvalues output in HZ in a logfile elmergui

### ISSUE THREAD

**Issue by labodezao** [ElmerCSC/elmerfem#235]
Hi !
Thanks for developping Elmer !
I would like to know if it's possible to : 
-1) Add a progression bar when a calculation is processing because the logfile is running too fast and It could be nice to have a progession bar to folow the progession of the computation,
-2 ) To be able to automaticly generale the logfile in text format,
-3 ) To add the frequency in Hz in the log file and in the Vtu file to have the information in paraview / elmer vtk because I did not found anyway to have this only on logfile (and in Omega ²)

Thanks by advance to telle me if it's (could be) possible

**Comment by raback** [comment]
SaveScalars has the option to save eigenvalues, I think it does that also in Hz.

Usually people run with command line and redirect the output to files. Then you can study that later on. Consider ElmerGUI mainly a tool to make the 1st sif file. Of course you can use that to run too but working with output is not something we will likely put effort to.
