### ISSUE TITLE
Linux (spack) of 8.4 fails due to this missing CMake fix

### ISSUE THREAD

**Issue by michaelkarlcoleman** [ElmerCSC/elmerfem#237]
The lack of this fix means that release 8.4 won't compile on Linux (at least not with Spack).  It's just a one-line fix, but should be applied to all branches, IMO.

https://github.com/ElmerCSC/elmerfem/commit/f02cb33acd59a32c41fe9f67367155e271c22ae8#

**Comment by raback** [comment]
This problem witg gcc/gfortran >= 10 has been addressed.
