### ISSUE TITLE
Devel branch fails to configure with Cmake

### ISSUE THREAD

**Issue by oparkins** [ElmerCSC/elmerfem#238]
CMake does not complete successfully because of a missing file `gittrack`. I've made a comment on the commit: https://github.com/ElmerCSC/elmerfem/commit/5fc7a3a224590492d3c0b04420c613d0761684b2#commitcomment-41928261

I would submit a pull request, but unfortunately I am not sure what the intention was with that commit. 

The steps to reproduce the problem are:
```
$ git clone https://github.com/ElmerCSC/elmerfem.git
$ mkdir build
$ cd build
$ cmake .. -D WITH_OpenMP:BOOLEAN=TRUE -D WITH_MPI:BOOLEAN=TRUE
...
...
...
CMake Error at fem/tests/mgdyn_wire_dbdt_line_element/CMakeLists.txt:5 (file):                                        
  file COPY cannot find                                                                                               
  "/home/oparkins/Build/elmerfem/fem/tests/mgdyn_wire_dbdt_line_element/wire_pair/dat/gittrack":                      
  No such file or directory.
```

**Comment by oparkins** [comment]
And it looks like it was merged into devel in this commit: 2f408d786d3759c881faf9a559552b55095aedaa

**Comment by ettaka** [comment]
@oparkins Thanks for report. This was me yesterday adding a few tests and forgot to add the file (there was another test with the same problem). Sorry! I added these files. Can you try to pull and test?

**Comment by oparkins** [comment]
@ettaka I just checked and it built fine for me (e78e41cb). Thanks for the timely fix!
