### ISSUE TITLE
Error: Rank mismatch between actual argument at (1) and actual argument at (2) (scalar and rank-1)

### ISSUE THREAD

**Issue by phoemur** [ElmerCSC/elmerfem#239]
#226 #231 

Can't compile with gfortran10 on Debian sid.
Need some help.
 Why is it building arpack stuff since I have it all already installed on my system ?
 Tx

```Scanning dependencies of target arpack
make[2]: Saindo do diretório '/home/phoemur/github/elmerfem/build'

make[2]: Entrando no diretório '/home/phoemur/github/elmerfem/build'

[ 45%] Building Fortran object mathlibs/src/arpack/CMakeFiles/arpack.dir/cgetv0.f.o
[ 45%] Building Fortran object mathlibs/src/arpack/CMakeFiles/arpack.dir/cnaitr.f.o
/home/phoemur/github/elmerfem/mathlibs/src/arpack/cnaitr.f:666:35:

  383 |             call svout (logfil, 1, rnorm, ndigit,
      |                                   2
......
  666 |             call svout (logfil, 2, rtemp, ndigit,
      |                                   1
Error: Rank mismatch between actual argument at (1) and actual argument at (2) (scalar and rank-1)
/home/phoemur/github/elmerfem/mathlibs/src/arpack/cnaitr.f:737:39:

  383 |             call svout (logfil, 1, rnorm, ndigit,
      |                                   2    
......
  737 |                 call svout (logfil, 2, rtemp, ndigit,
      |                                       1
Error: Rank mismatch between actual argument at (1) and actual argument at (2) (scalar and rank-1)
make[2]: *** [mathlibs/src/arpack/CMakeFiles/arpack.dir/build.make:76: mathlibs/src/arpack/CMakeFiles/arpack.dir/cnaitr.f.o] Erro 1
make[2]: Saindo do diretório '/home/phoemur/github/elmerfem/build'

make[1]: *** [CMakeFiles/Makefile2:23382: mathlibs/src/arpack/CMakeFiles/arpack.dir/all] Erro 2
make[1]: Saindo do diretório '/home/phoemur/github/elmerfem/build'

make: *** [Makefile:163: all] Erro 2 ```

**Comment by phoemur** [comment]
-- The Fortran compiler identification is GNU 10.2.0
-- The C compiler identification is GNU 9.3.0
-- The CXX compiler identification is GNU 10.2.0
-- Check for working Fortran compiler: /usr/bin/f95
-- Check for working Fortran compiler: /usr/bin/f95  -- works
-- Detecting Fortran compiler ABI info
-- Detecting Fortran compiler ABI info - done
-- Checking whether /usr/bin/f95 supports Fortran 90
-- Checking whether /usr/bin/f95 supports Fortran 90 -- yes
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Checking whether GFortran version >= 4.8 -- yes
-- Try OpenMP C flag = [-fopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Success
-- Try OpenMP CXX flag = [-fopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Success
-- Try OpenMP Fortran flag = [-fopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Success
-- Found OpenMP: -fopenmp  
-- Checking whether /usr/bin/f95 supports OpenMP 4.0
-- Checking whether /usr/bin/f95 supports OpenMP 4.0 -- yes
-- Checking whether /usr/bin/f95 supports OpenMP 4.5
-- Checking whether /usr/bin/f95 supports OpenMP 4.5 -- yes
-- ------------------------------------------------
-- Mesh adaptation 2D/3D looking for [Mmg] tools 
--   Mmg:           TRUE
--   Mmg_INC:       /usr/local/include
--   Mmg_LIB:      /usr/local/lib/libmmg.a
--   Mmg_LIBDIR:      /usr/local/lib
-- Compile MMG2DSolver/MMG3DSolver
-- ------------------------------------------------
-- ------------------------------------------------
-- Looking for Fortran sgemm
-- Looking for Fortran sgemm - not found
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE  
-- Looking for Fortran sgemm
-- Looking for Fortran sgemm - found
-- Found BLAS: /usr/lib/x86_64-linux-gnu/libopenblas.so  
-- Looking for Fortran cheev
-- Looking for Fortran cheev - found
-- A library with LAPACK API found.
-- Checking whether /usr/bin/f95 supports PROCEDURE POINTER
-- Checking whether /usr/bin/f95 supports PROCEDURE POINTER -- yes
-- Checking whether /usr/bin/f95 supports CONTIGUOUS
-- Checking whether /usr/bin/f95 supports CONTIGUOUS -- yes
-- Checking whether /usr/bin/f95 supports EXECUTE_COMMAND_LINE
-- Checking whether /usr/bin/f95 supports EXECUTE_COMMAND_LINE -- yes
CMake Warning (dev) at /usr/share/cmake-3.16/Modules/CheckIncludeFiles.cmake:120 (message):
  Policy CMP0075 is not set: Include file check macros honor
  CMAKE_REQUIRED_LIBRARIES.  Run "cmake --help-policy CMP0075" for policy
  details.  Use the cmake_policy command to set the policy and suppress this
  warning.

  CMAKE_REQUIRED_LIBRARIES is set to:

    /usr/lib/x86_64-linux-gnu/libopenblas.so;/usr/lib/x86_64-linux-gnu/libopenblas.so

  For compatibility with CMake 3.11 and below this check is ignoring it.
Call Stack (most recent call first):
  matc/CMakeLists.txt:4 (CHECK_INCLUDE_FILES)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Looking for include file inttypes.h
-- Looking for include file inttypes.h - found
-- Looking for sys/types.h
CMake Warning (dev) at /usr/share/cmake-3.16/Modules/CheckIncludeFile.cmake:80 (message):
  Policy CMP0075 is not set: Include file check macros honor
  CMAKE_REQUIRED_LIBRARIES.  Run "cmake --help-policy CMP0075" for policy
  details.  Use the cmake_policy command to set the policy and suppress this
  warning.

  CMAKE_REQUIRED_LIBRARIES is set to:

    /usr/lib/x86_64-linux-gnu/libopenblas.so;/usr/lib/x86_64-linux-gnu/libopenblas.so

  For compatibility with CMake 3.11 and below this check is ignoring it.
Call Stack (most recent call first):
  /usr/share/cmake-3.16/Modules/CheckTypeSize.cmake:230 (check_include_file)
  fem/CMakeLists.txt:47 (CHECK_TYPE_SIZE)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of long
-- Check size of long - done
-- Found 124 modules from /home/phoemur/github/elmerfem/fem/src/modules
--  ELMERSOLVER_RPATH_STRING_MOD $ORIGIN/../lib/elmersolver:/usr/local/lib
--  ELMERLIB_RPATH_STRING $ORIGIN/:/usr/local/lib
-- Found 675 tests
-- Looking for execinfo.h
CMake Warning (dev) at /usr/share/cmake-3.16/Modules/CheckIncludeFile.cmake:80 (message):
  Policy CMP0075 is not set: Include file check macros honor
  CMAKE_REQUIRED_LIBRARIES.  Run "cmake --help-policy CMP0075" for policy
  details.  Use the cmake_policy command to set the policy and suppress this
  warning.

  CMAKE_REQUIRED_LIBRARIES is set to:

    /usr/lib/x86_64-linux-gnu/libopenblas.so;/usr/lib/x86_64-linux-gnu/libopenblas.so

  For compatibility with CMake 3.11 and below this check is ignoring it.
Call Stack (most recent call first):
  elmergrid/src/metis-5.1.0/GKlib/GKlibSystem.cmake:97 (check_include_file)
  elmergrid/src/metis-5.1.0/CMakeLists.txt:21 (include)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Looking for execinfo.h - found
-- Looking for getline
-- Looking for getline - found
-- checking for thread-local storage - found
-- ------------------------------------------------
--   BLAS library:   /usr/lib/x86_64-linux-gnu/libopenblas.so
--   LAPACK library: /usr/lib/x86_64-linux-gnu/libopenblas.so
-- ------------------------------------------------
--   Fortran compiler:        /usr/bin/f95
--   Fortran flags:            -fopenmp -O2 -g -DNDEBUG
-- ------------------------------------------------
--   C compiler:              /usr/bin/cc
--   C flags:                  -fopenmp -O2 -g -DNDEBUG
-- ------------------------------------------------
--   CXX compiler:            /usr/bin/c++
--   CXX flags:                -fopenmp -O2 -g -DNDEBUG
-- ------------------------------------------------
-- ------------------------------------------------
--   Package filename: elmerfem-8.4-41c4d0f4-20200917_Linux-x86_64 
--   Patch version: 8.4-41c4d0f4 
-- Configuring done
-- Generating done
-- Build files have been written to: /home/phoemur/github/elmerfem/build

**Comment by phoemur** [comment]
* I noticed a mismatch between my compiler versions above, but i fixed it and still got the same error:
-- The Fortran compiler identification is GNU 10.2.0
-- The C compiler identification is GNU 10.2.0
-- The CXX compiler identification is GNU 10.2.0
-- Check for working Fortran compiler: /usr/bin/f95
-- Check for working Fortran compiler: /usr/bin/f95  -- works

**Comment by juharu** [comment]
Hi 

In my opinion it is somewhat unfortunate that gfortran flags the age old and very common fortran 77 habit 
this way in new versions, but it is what it is, i guess. Options "-allow-argument-mismatch" and/or "-std=legacy" 
will get you through. 

We should update the cmake configuration of our F77 libraries, I guess. 

Br, Juha

**Comment by juharu** [comment]
>"-allow-argument-mismatch> 
"-fallow-argument-mismatch" 

...

**Comment by phoemur** [comment]
Works like a charm. Thanks so much!!

Just used -DCMAKE_Fortran_FLAGS=-fallow-argument-mismatch

In my interpretation, this sometimes can happen when using a Fortran95 compiler on F77 code, so as in this Stackoverflow topic:
https://stackoverflow.com/questions/45164502/rank-mismatch-in-argument-error-in-fortran-77-not-being-reported
