### ISSUE TITLE
"Error: Rank mismatch ..." at cnaitr.f

### ISSUE THREAD

**Issue by Foadsf** [ElmerCSC/elmerfem#240]
Compiling on macOS I'm getting the below error:

~~~
elmerfem/mathlibs/src/arpack/cnaitr.f:666:35:

  383 |             call svout (logfil, 1, rnorm, ndigit,
      |                                   2
......
  666 |             call svout (logfil, 2, rtemp, ndigit,
      |                                   1
Error: Rank mismatch between actual argument at (1) and actual argument at (2) (scalar and rank-1)
elmerfem/mathlibs/src/arpack/cnaitr.f:737:39:

  383 |             call svout (logfil, 1, rnorm, ndigit,
      |                                   2    
......
  737 |                 call svout (logfil, 2, rtemp, ndigit,
      |                                       1
Error: Rank mismatch between actual argument at (1) and actual argument at (2) (scalar and rank-1)
make[2]: *** [mathlibs/src/arpack/CMakeFiles/arpack.dir/cnaitr.f.o] Error 1
make[1]: *** [mathlibs/src/arpack/CMakeFiles/arpack.dir/all] Error 2
make: *** [all] Error 2
 ?
~~~

**Comment by raback** [comment]
I used sed to replace calls to svout when the 2nd parameter is 1 with ssout which expects that n==1. This is in thread arpack_svout. Maybe you can test this out. I understand that this is a temporal fix as long as the bundled library is used.

**Comment by juharu** [comment]
Hi 
This problem surfaces when compiling with newer gcc versions. And ARPACK source is not the only place within Elmer source code repository 
that use this type of construct. In fact, this is very typical fortran 77 coding and even some of our own f90 codes will break with calls to fortran 
77 libraries. The remedy for now is to add compiler flags, either "-fallow-argument-mismatch" or "-std=legacy", we should maybe update 
our cmake accordingly. 
Juha

**Comment by raback** [comment]
Hi



Yes, this was fixed already like that in this pull request



https://github.com/ElmerCSC/elmerfem/pull/234/commits/b5fb4203c630741d91e5376bc3a2972f7f80e53c



However, on some platforms this broke the compilation. Maybe having this 
only apply to some modules would help. I must say that I didn’t look the 
resulting errors in detail. I thought that these would be limited to arpack 
but I guess not…



-Peter

**Comment by juharu** [comment]
Should perhaps limit the change to apply to only recent gcc versions - or somethiing ? Or maybe better luck with "-std=legacy".

**Comment by Foadsf** [comment]
replaced all the `svout(logfil, 1,`s with `ssout(logfil, 1,`. But now the same issue with `ivout(logfil, 1,)`! any replacement for `ivout`?

**Comment by Foadsf** [comment]
Replacing `svout`s with `ssout`s was a bad idea leading to lot's of other errors. I just added 

~~~
if("${CMAKE_Fortran_COMPILER_ID}" MATCHES "GNU")
  set(CMAKE_Fortran_FLAGS "${CMAKE_Fortran_FLAGS} -std=legacy")
endif()
~~~

to the root `CMakeLists.txt` and it seems to be compiling.

**Comment by Foadsf** [comment]
and we need to use this horrible part in order to help CMake find `gcc` and `g++` installed via HomeBrew:

~~~
if(APPLE)
  set(CMAKE_C_COMPILER "/usr/local/bin/gcc-10")
  set(CMAKE_CXX_COMPILER "/usr/local/bin/g++-10")
  set(CMAKE_Fortran_COMPILER "/usr/local/bin/gfortran")
endif()
~~~

**Comment by raback** [comment]
Ok, great. Let's go with the "-std=legacy" flag then. At least this flag is known also for the older compilers. Foad, will you make a pull request?

**Comment by Foadsf** [comment]
I had to run 

~~~
install_name_tool -change @rpath/<some_library>.dylib /usr/local/lib/elmersolver/<some_library>.dylib /usr/local/bin/ElmerSolver
~~~

for `<some_library>` as `libelmersolver`, `libmatc`, `libparpack`, `libarpack`, and `libfhuti` in order to get the `ElmerSolver` running! I have no idea why.

**Comment by Foadsf** [comment]
@raback FYI

https://github.com/ElmerCSC/elmerfem/pull/241

**Comment by raback** [comment]
This seems to have fixed this with minimal changes. We only apply this to gcc >= 10. 
# Get rid of the annoying rank mismatch warning
IF("${CMAKE_Fortran_COMPILER_ID}" MATCHES "GNU")
  IF(CMAKE_CXX_COMPILER_VERSION VERSION_GREATER 9.9)
    SET(CMAKE_Fortran_FLAGS "${CMAKE_Fortran_FLAGS} -fallow-argument-mismatch")
  ENDIF()
ENDIF()
