### ISSUE TITLE
As for the quadratic edge element, can you provide its basis function in two dimensions and its definition of degrees of freedom? Or what is the basis for writing quadratic edge elements?    

### ISSUE THREAD

**Issue by HaoWangCyy** [ElmerCSC/elmerfem#248]

**Comment by mmalinen** [comment]
The local FE spaces for the second-order edge elements are described in the section F.2.3 of the appendix F in the ElmerSolver Manual

http://www.nic.funet.fi/pub/sci/physics/elmer/doc/ElmerSolverManual.pdf

With <.,.>_D denoting L2 inner product over a domain D, the values of the DOFs which are associated with the edges are defined as D = S*<g.e,v>_E where the unit vector e is tangential to the edge, g is vector-valued data, v = Basis(2)-Basis(1) is the difference of the nodal basis functions on the edge E, and S reverts sign if necessary. Then there are additional bubble basis functions which vanish on the edges and are constructed directly without thinking in terms of DOFs in the first place.

**Comment by HaoWangCyy** [comment]
Thanks a lot！Let me learn! May encounter do not understand the place, but also ask you! Thank you again.

 
I wish you good health and good work.

--

Best regards,
Hao Wang (王昊)

School of Mathematics and
Computational Science,
Xiangtan University,
Xiangtan, 411105.
wanghao106031@126.com;

283105210@qq.com;
(Tel:) (+86)18873220835
 




At 2020-11-19 15:42:46, "mmalinen" <notifications@github.com> wrote:

The local FE spaces for the second-order edge elements are described in the section F.2.3 of the appendix F in the ElmerSolver Manual

http://www.nic.funet.fi/pub/sci/physics/elmer/doc/ElmerSolverManual.pdf

With <.,.>_D denoting L2 inner product over a domain D, the values of the DOFs which are associated with the edges are defined as D = S*<g.e,v>_E where the unit vector e is tangential to the edge, g is vector-valued data, v = Basis(2)-Basis(1) is the difference of the nodal basis functions on the edge E, and S reverts sign if necessary. Then there are additional bubble basis functions which vanish on the edges and are constructed directly without thinking in terms of DOFs in the first place.

**Comment by HaoWangCyy** [comment]
I read that ：In the case of triangles and tetrahedra the reference element space is given by (F.7) with k = 2 and thus

has the dimension 8 or 20, respectively.  But for the case of triangles reference element，I can't write these 8 basis functions. As we know，the lowest edge elem has 3 dofs in  a triangle and the expression of its degree of freedom and basis function are given.  Although it described in the section F.2.3，It's very abstract. Can you directly give the form of quadratic basis function （8 basis functions） in a class of trigonometric elements？Let's ask a question: are all degrees of freedom equal to the one you wrote？




--

Best regards,
Hao Wang (王昊)

School of Mathematics and
Computational Science,
Xiangtan University,
Xiangtan, 411105.
wanghao106031@126.com;

283105210@qq.com;
(Tel:) (+86)18873220835
 




At 2020-11-19 15:42:46, "mmalinen" <notifications@github.com> wrote:

The local FE spaces for the second-order edge elements are described in the section F.2.3 of the appendix F in the ElmerSolver Manual

http://www.nic.funet.fi/pub/sci/physics/elmer/doc/ElmerSolverManual.pdf

With <.,.>_D denoting L2 inner product over a domain D, the values of the DOFs which are associated with the edges are defined as D = S*<g.e,v>_E where the unit vector e is tangential to the edge, g is vector-valued data, v = Basis(2)-Basis(1) is the difference of the nodal basis functions on the edge E, and S reverts sign if necessary. Then there are additional bubble basis functions which vanish on the edges and are constructed directly without thinking in terms of DOFs in the first place.

**Comment by mmalinen** [comment]
The second-order basis is hierarchic, so the three basis functions of the lowest-order basis are also used as basis functions in the second-order case. The most concrete expressions of the local basis functions over the reference element are given within the function EdgeElementInfo in ElementDescription.F90

https://github.com/ElmerCSC/elmerfem/blob/devel/fem/src/ElementDescription.F90

I think for the reference triangle the following symbolic math software commands may be used to produce the basis functions w1,..., w6 associated with the edges

```
L1[x_,y_] := 1/2 * (1-x-1/Sqrt[3]*y)
L2[x_,y_] := 1/2 * (1+x-1/Sqrt[3]*y)
L3[x_,y_] := Sqrt[3]/3 * y

g1 = D[L1[u,v],{{u,v}}]
g2 = D[L2[u,v],{{u,v}}]
g3 = D[L3[u,v],{{u,v}}]

fun1 = L1[u,v]*(L1[u,v]*g2 - L2[u,v]*g1)
fun2 = L2[u,v]*(L1[u,v]*g2 - L2[u,v]*g1)

fun3 = L2[u,v]*(L2[u,v]*g3 - L3[u,v]*g2)
fun4 = L3[u,v]*(L2[u,v]*g3 - L3[u,v]*g2)

fun5 = L3[u,v]*(L3[u,v]*g1 - L1[u,v]*g3)
fun6 = L1[u,v]*(L3[u,v]*g1 - L1[u,v]*g3)

w1 = Simplify[fun1 + fun2]
w2 = Simplify[3*(fun2 - fun1)]

w3 = Simplify[fun3 + fun4]
w4 = Simplify[3*(fun4 - fun3)]

w5 = Simplify[fun5 + fun6]
w6 = Simplify[3*(fun6 - fun5)]
```


For the bubble basis functions any couple of the following three basis functions
may be selected

```
fun7 = Simplify[L3[u,v]*(L1[u,v]*g2 - L2[u,v]*g1)]
fun8 = Simplify[L2[u,v]*(L1[u,v]*g3 - L3[u,v]*g1)]
fun9 = Simplify[L1[u,v]*(L2[u,v]*g3 - L3[u,v]*g2)]
```

What couple of the candidate functions is chosen depends on the global indexing of the element nodes. For details of this choice the Fortran file is the best resource.

**Comment by HaoWangCyy** [comment]
Thank you very much for your reply. In the communication with you, I have learned a lot. 




Thank you again! I wish you good health and smooth work!




--

Best regards,
Hao Wang (王昊)

School of Mathematics and
Computational Science,
Xiangtan University,
Xiangtan, 411105.
wanghao106031@126.com;

283105210@qq.com;
(Tel:) (+86)18873220835
 




At 2020-11-19 20:28:03, "mmalinen" <notifications@github.com> wrote:

The second-order basis is hierarchic, so the three basis functions of the lowest-order basis are also used as basis functions in the second-order case. The most concrete expressions of the local basis functions over the reference element are given within the function EdgeElementInfo in ElementDescription.F90

https://github.com/ElmerCSC/elmerfem/blob/devel/fem/src/ElementDescription.F90

I think for the reference triangle the following symbolic math software commands may be used to produce the basis functions w1,..., w6 associated with the edges

L1[x_,y_] := 1/2 * (1-x-1/Sqrt[3]*y)
L2[x_,y_] := 1/2 * (1+x-1/Sqrt[3]*y)
L3[x_,y_] := Sqrt[3]/3 * y

g1 = D[L1[u,v],{{u,v}}]
g2 = D[L2[u,v],{{u,v}}]
g3 = D[L3[u,v],{{u,v}}]

fun1 = L1[u,v]*(L1[u,v]*g2 - L2[u,v]*g1)
fun2 = L2[u,v]*(L1[u,v]*g2 - L2[u,v]*g1)

fun3 = L2[u,v]*(L2[u,v]*g3 - L3[u,v]*g2)
fun4 = L3[u,v]*(L2[u,v]*g3 - L3[u,v]*g2)

fun5 = L3[u,v]*(L3[u,v]*g1 - L1[u,v]*g3)
fun6 = L1[u,v]*(L3[u,v]*g1 - L1[u,v]*g3)

w1 = Simplify[fun1 + fun2]
w2 = Simplify[3*(fun2 - fun1)]

w3 = Simplify[fun3 + fun4]
w4 = Simplify[3*(fun4 - fun3)]

w5 = Simplify[fun5 + fun6]
w6 = Simplify[3*(fun6 - fun5)]


For the bubble basis functions any couple of the following three basis functions
may be selected

fun7 = Simplify[L3[u,v]*(L1[u,v]*g2 - L2[u,v]*g1)]
fun8 = Simplify[L2[u,v]*(L1[u,v]*g3 - L3[u,v]*g1)]
fun9 = Simplify[L1[u,v]*(L2[u,v]*g3 - L3[u,v]*g2)]


What couple of the candidate functions is chosen depends on the global indexing of the element nodes. For details of this choice the Fortran file is the best resource.
