### ISSUE TITLE
ElmerGrid mesh.names mismatch when converting Gmsh file

### ISSUE THREAD

**Issue by ajpina** [ElmerCSC/elmerfem#249]
Hi,
The surface names in mesh.name file mismatches those coming from surface physical groups in a Gmsh file even though the output when running ElmerGrid identifies the names correctly.
This is an example:

`ElmerGrid 14 2 gmsh_file.msh -2d -out elmermesh` 

Part of the output after running ElmerGrid is like this:

Elmergrid loading data:
-----------------------
Elapsed time (s): 0.00 0.00
Format chosen using the first line: $MeshFormat
Gmsh version is 4.1
Loading mesh in Gmsh format 4.1 from file ELMER_simulation.msh
Reading 95 entities in 0D
Reading 106 entities in 1D
Reading 19 entities in 2D
Allocating for 7696 knots and 15630 elements.
Boundary name for physical group 20 is: MASTER_ROTOR_BOUNDARY
Boundary name for physical group 21 is: SLAVE_ROTOR_BOUNDARY
Boundary name for physical group 22 is: SB_ROTOR_BOUNDARY
Boundary name for physical group 23 is: MASTER_STATOR_BOUNDARY
Boundary name for physical group 24 is: SLAVE_STATOR_BOUNDARY
Boundary name for physical group 25 is: SB_STATOR_BOUNDARY
Boundary name for physical group 26 is: AIRGAP_ARC_BOUNDARY
Boundary name for physical group 27 is: VP0_BOUNDARY
Body name for physical group 1 is: Shaft
Body name for physical group 2 is: Hole_Rotor_R0_T0_S0
Body name for physical group 3 is: HoleMagnet_Rotor_Parallel_N_R0_T0_S0
Body name for physical group 4 is: Hole_Rotor_R0_T1_S0
Body name for physical group 5 is: HoleMagnet_Rotor_Parallel_N_R0_T1_S0
Body name for physical group 6 is: Hole_Rotor_R0_T2_S0
Body name for physical group 7 is: Lamination_Rotor_Bore_Radius_Ext
Body name for physical group 8 is: Lamination_Stator_Bore_Radius_Int
Body name for physical group 9 is: Wind_Stator_R0_T0_S0
Body name for physical group 10 is: Wind_Stator_R0_T0_S1
Body name for physical group 11 is: Wind_Stator_R0_T0_S2
Body name for physical group 12 is: Wind_Stator_R0_T0_S3
Body name for physical group 13 is: Wind_Stator_R0_T0_S4
Body name for physical group 14 is: Wind_Stator_R0_T0_S5
Body name for physical group 15 is: Airgap_int
Body name for physical group 16 is: SlidingBand_int
Body name for physical group 17 is: SlidingBand_ext
Body name for physical group 18 is: Airgap_ext
Body name for physical group 19 is: Airbox
Allocating lookup table for tags of size 106
....

And the resulting mesh.name file is as follows:

! ----- names for bodies -----
$ Shaft = 1
$ Hole_Rotor_R0_T0_S0 = 2
$ HoleMagnet_Rotor_Parallel_N_R0Hole_Rotor_R0_T1_S0 = 3
$ Hole_Rotor_R0_T1_S0 = 4
$ HoleMagnet_Rotor_Parallel_N_R0Hole_Rotor_R0_T2_S0 = 5
$ Hole_Rotor_R0_T2_S0 = 6
$ Lamination_Rotor_Bore_Radius_ELamination_Stator_Bore_Radius_Wind_Stator_R0_T0_S0 = 7
$ Lamination_Stator_Bore_Radius_Wind_Stator_R0_T0_S0 = 8
$ Wind_Stator_R0_T0_S0 = 9
$ Wind_Stator_R0_T0_S1 = 10
$ Wind_Stator_R0_T0_S2 = 11
$ Wind_Stator_R0_T0_S3 = 12
$ Wind_Stator_R0_T0_S4 = 13
$ Wind_Stator_R0_T0_S5 = 14
$ Airgap_int = 15
$ SlidingBand_int = 16
$ SlidingBand_ext = 17
$ Airgap_ext = 18
$ Airbox = 19
! ----- names for boundaries -----
$ MASTER_ROTOR_BOUNDARY = 20
$ SLAVE_ROTOR_BOUNDARY = 21
$ SB_ROTOR_BOUNDARY = 22
$ MASTER_STATOR_BOUNDARY = 23
$ SLAVE_STATOR_BOUNDARY = 24
$ AIRGAP_ARC_BOUNDARY = 26
$ VP0_BOUNDARY = 27

Please take a look at bodies 3, 5, 7 and 8. I also tried with options 'autoclean' and 'nonames' but results seem to be the same. Gmsh file is included for your perusal.

Thanks,
Alejandro
[ELMER_simulation.msh.zip](https://github.com/ElmerCSC/elmerfem/files/5609993/ELMER_simulation.msh.zip)

**Comment by raback** [comment]
Hi, you had pretty long names. The max was hard coded to 30 which was a little short. Then the 1st break came only after some entry was less than 30. I changed this to 50. It should be of course dynamic but it is what it is ;-) Thanx for reporting!
