### ISSUE TITLE
compile error: Type mismatch in argument ‘met’ at (1); passed INTEGER(4) to INTEGER(8)

### ISSUE THREAD

**Issue by yushuoliu** [ElmerCSC/elmerfem#255]
HI
When I "make" Elmer/Ice, I get error information: 
--------------------------------------------------
[ 64%] Building Fortran object elmerice/Solvers/CMakeFiles/ElmerIceSolvers.dir/CalvingRemeshMMG.F90.o
/home/ys-l/elmerice/elmerice/Solvers/CalvingRemeshMMG.F90:432:45:

  432 |       CALL MMG3D_mmg3dls(mmgMesh,mmgSol,ierr)
      |                                             1
Error: Type mismatch in argument ‘met’ at (1); passed INTEGER(4) to INTEGER(8)
make[2]: *** [elmerice/Solvers/CMakeFiles/ElmerIceSolvers.dir/build.make:1103：elmerice/Solvers/CMakeFiles/ElmerIceSolvers.dir/CalvingRemeshMMG.F90.o] error 1
make[1]: *** [CMakeFiles/Makefile2:16735：elmerice/Solvers/CMakeFiles/ElmerIceSolvers.dir/all] error 2
make: *** [Makefile:163：all] error 2
---------------------------------------------------
I don't know how to fix this error, I think it maybe, need to modify the code file, and I can't get the solution on internet.
I do this work at Ubuntu20.04
need help!
Thanks for any help!
Best regrads!
Yushuo Liu

**Comment by tzwinger** [comment]
MMG API has changed - plan is to change code and demand MMG version >= 5.5 in Cmake

**Comment by joeatodd** [comment]
Some progress on this for the 3D code: 9d6394ac7f88581478df3ef48d65052286b70d40 

For now we are leaving the metric argument blank, but 5.5 actually allows the isosurface discretisation (calving) and mesh refinement to happen in all at once. So, in future we will probably make use of the metric argument.
