### ISSUE TITLE
Bug during compilation

### ISSUE THREAD

**Issue by vulkomilev** [ElmerCSC/elmerfem#262]
HI while I was following your steps I got this error:
`-- Checking whether GFortran version >= 4.8 -- yes
-- Checking whether /usr/bin/f95 supports OpenMP 4.0
-- Checking whether /usr/bin/f95 supports OpenMP 4.0 -- yes
-- Checking whether /usr/bin/f95 supports OpenMP 4.5
-- Checking whether /usr/bin/f95 supports OpenMP 4.5 -- yes
-- ------------------------------------------------
-- Mesh adaptation 2D/3D looking for [Mmg] tools 
--   Library not found: >MMG_FOUND< 
--     Missing: >MMG_INCLUDE_DIR< , >MMG_LIBRARY<, to compile MMG3DSolver
-- ------------------------------------------------
-- A library with LAPACK API found.
-- Checking whether /usr/bin/f95 supports PROCEDURE POINTER
-- Checking whether /usr/bin/f95 supports PROCEDURE POINTER -- yes
-- Checking whether /usr/bin/f95 supports CONTIGUOUS
-- Checking whether /usr/bin/f95 supports CONTIGUOUS -- yes
-- Checking whether /usr/bin/f95 supports EXECUTE_COMMAND_LINE
-- Checking whether /usr/bin/f95 supports EXECUTE_COMMAND_LINE -- yes
-- Found 125 modules from /home/<username>/<projectDir>/elmerfem/fem/src/modules
--  ELMERSOLVER_RPATH_STRING_MOD $ORIGIN/../lib/elmersolver
--  ELMERLIB_RPATH_STRING $ORIGIN/
-- Skipping test PoissonDG with 16 procs
-- Skipping test WinkelPoissonMetisKwayDual with 16 procs
-- Skipping test WinkelPoissonMetisKwayNodal with 16 procs
-- Found 691 tests
-- checking for thread-local storage - found
-- ------------------------------------------------
--   BLAS library:   /usr/lib/x86_64-linux-gnu/libblas.so
--   LAPACK library: /usr/lib/x86_64-linux-gnu/liblapack.so;/usr/lib/x86_64-linux-gnu/libblas.so
-- ------------------------------------------------
--   Fortran compiler:        /usr/bin/f95
--   Fortran flags:            -fopenmp -O3 -DNDEBUG -O3
-- ------------------------------------------------
--   C compiler:              /usr/bin/cc
--   C flags:                  -fopenmp -O3 -DNDEBUG
-- ------------------------------------------------
--   CXX compiler:            /usr/bin/c++
--   CXX flags:                -fopenmp -O3 -DNDEBUG
-- ------------------------------------------------
--   MPI Fortran:             TRUE
--   MPI Fortran compiler:    /usr/bin/mpif90
--   MPI Fortran flags:       
--   MPI Fortran include dir: /usr/lib/x86_64-linux-gnu/openmpi/include;/usr/lib/x86_64-linux-gnu/openmpi/lib
--   MPI Fortran libraries:   /usr/lib/x86_64-linux-gnu/openmpi/lib/libmpi_usempif08.so;/usr/lib/x86_64-linux-gnu/openmpi/lib/libmpi_usempi_ignore_tkr.so;/usr/lib/x86_64-linux-gnu/openmpi/lib/libmpi_mpifh.so;/usr/lib/x86_64-linux-gnu/openmpi/lib/libmpi.so
--   MPI Fortran link flags:  
-- ------------------------------------------------
--   MPI C:             TRUE
--   MPI C compiler:    /usr/bin/mpicc
--   MPI C flags:       
--   MPI C include dir: /usr/lib/x86_64-linux-gnu/openmpi/include/openmpi;/usr/lib/x86_64-linux-gnu/openmpi/include
--   MPI C libraries:   /usr/lib/x86_64-linux-gnu/openmpi/lib/libmpi.so
--   MPI C flags:       
-- ------------------------------------------------
-- ------------------------------------------------
--   Package filename: elmerfem-9.0-fee0e53e-20210228_Linux-x86_64 
--   Patch version: 9.0-fee0e53e 
-- Configuring done
CMake Error at cmake/Modules/AddModules.cmake:27 (ADD_LIBRARY):
  No SOURCES given to target: CMakeFiles
Call Stack (most recent call first):
  cmake/Modules/AddModules.cmake:64 (ADD_ELMER_MODULE)
  fem/src/modules/CMakeLists.txt:5 (ADD_ELMER_MODULES)

CMake Generate step failed.  Build files cannot be regenerated correctly.
`
on the step 
`cmake .. -DWITH_OpenMP:BOOLEAN=TRUE -DWITH_MPI:BOOLEAN=TRUE
`

**Comment by raback** [comment]
What is your platform? And when you refer to "your steps" what instructions do you mean?

**Comment by vulkomilev** [comment]
What is your platform?
Ubuntu 20.04
And when you refer to "your steps" what instructions do you mean?
I am using the steps from the readme

**Comment by raback** [comment]
The instructions should be checked. In the meantime for Ubuntu 20.04 Launchpad should work, see http://www.elmerfem.org/blog/binaries/
