### ISSUE TITLE
Windows GUI: Hyperlinks in About dialog not copyable / clickable

### ISSUE THREAD

**Issue by bevanweiss** [ElmerCSC/elmerfem#267]
When trying to access additional information about ElmerGUI it would be nice if the About dialog allowed for copying / clicking directly on the hyperlinks within it to access the online content

![image](https://user-images.githubusercontent.com/2055446/113132002-9d1bd380-9269-11eb-9c5a-dd1427eade73.png)

**Comment by raback** [comment]
Saeki implemented this issue. Thanx Saeki! I close this one.
