### ISSUE TITLE
GUI: Resizing Material Library dialog box doesn't result in useful resize

### ISSUE THREAD

**Issue by bevanweiss** [ElmerCSC/elmerfem#268]
When resizing the Material Library dialog, the dialog itself increases in size, but the usable controls within do not shift to utilise the new size of the dialog.

![image](https://user-images.githubusercontent.com/2055446/113132434-2af7be80-926a-11eb-97a8-19c4983a4748.png)

**Comment by raback** [comment]
Saeki implemented this issue. Thanx Saeki!
