### ISSUE TITLE
Wrong argument in CommunicateMeshPieces call to CheckBuffer

### ISSUE THREAD

**Issue by Azrael3000** [ElmerCSC/elmerfem#273]
In MeshPartition.F90:2343 you have:

      CALL CheckBuffer( nl + ni*4 + nr*8 + (NoPartitions-1)* ( 4*2 + & 
           2*MPI_BSEND_OVERHEAD ) )

This calculation is wrong for several reasons:

1. In `checkBuffer` the incoming size is multiplied by 4 (see `SParIterComm.F90:89`) so it makes no sense to multiply `ni` by 4 and `nr` by 8. I suspect the idea was that 4 and 8 represent `sizeof(int/double`) but a better way to handle this would be to use `MPI_Pack_size` see: https://www.mpich.org/static/docs/v4.0a1/www3/MPI_Buffer_attach.html and get rid of that `*4` in `checkBuffer` (obviously requiring a rewrite of all calls to that function.
2. The `4*2` should be `3*sizeof(int)` as there are 3 integer BSENDS, again using `MPI_Pack_Size` would be sensible.
3. The `2*MPI_BSEND_OVERHEAD` should also be `3*...` as there can be 3 concurent BSENDs active in this routine

So to summarize: This routine allocates too much memory for MPI due to the `4*n` in `CheckBuffer`  which saves the day as the calculation as it is, is wrong.

If someone reviews this, I strongly suggest to have a look at all CheckBuffer calls as there might be more such issues floating around.

Sorry for the C notation, my Fortran is a bit rusty.

Best,
Arno

Edit: I have a problem in another code part and that is the `ExchangeInterfaces` function in `SParIterComm`. I actually think the `BSEND` that are in this function is rather mostly useless for the matrix sends. They should be replaced by `ISEND` as their memory will be available anyways (except for the first 2 obviously). Same for the following `ExchangeIfvalues` function.

The same holds true for the `BSEND`s in `CommunicateMeshPieces`

**Comment by raback** [comment]
To my understanding this has to been fixed.
