### ISSUE TITLE
DCRComplexSolve.F90 compile error

### ISSUE THREAD

**Issue by jklalkdjfha** [ElmerCSC/elmerfem#274]
While compiling Elmer on Fedora 34, I get a bunch of errors like

```
elmerfem/fem/src/modules/DCRComplexSolve.F90:512:35:

  341 |                    'Bvector', Model % BCs(i) % Values,  n, NodeIndexes )
      |                                                                        2
......
  512 |          DO i=1,MIN(3,SIZE(Hwrk,2))
      |                                   1
Error: Index variable ‘i’ redefined at (1) in procedure ‘inputvector’ called from within DO loop at (2)

> gfortran --version
GNU Fortran (GCC) 11.1.1 20210428 (Red Hat 11.1.1-1)

```
The whole log is attached.

This is the only file having problems and it is easily fixed by declaring i and j in every affected function. I attached a patch that fixes the issue for me. I don't remember enough about Fortran to understand why this ever worked.

Error log: [DCRComplexSolve-compile-error.txt](https://github.com/ElmerCSC/elmerfem/files/6411137/DCRComplexSolve-compile-error.txt)

Patch: [0001-fixed-DCRComplexSolve-compile-error.patch](https://github.com/ElmerCSC/elmerfem/files/6411138/0001-fixed-DCRComplexSolve-compile-error.patch.txt)

**Comment by raback** [comment]
Thanx for reporting! I think this was fixed in
96a33930ee23e785f33bcb257398f1ccca8fdf99
