### ISSUE TITLE
 CheckLinearSolverOptions: MUMPS solver has not been installed.

### ISSUE THREAD

**Issue by ouening** [ElmerCSC/elmerfem#275]
Hi, when I run the example `Electrokinetics` provided by `tutorials-GUI-files.zip`, I got errors:
```
ELMER SOLVER (v 9.0) STARTED AT: 2021/05/05 11:34:30

ParCommInit:  Initialize #PEs:            1
MAIN: 
MAIN: =============================================================
MAIN: ElmerSolver finite element software, Welcome!
MAIN: This program is free software licensed under (L)GPL
MAIN: Copyright 1st April 1995 - , CSC - IT Center for Science Ltd.
MAIN: Webpage http://www.csc.fi/elmer, Email elmeradm@csc.fi
MAIN: Version: 9.0 (Rev: Release, Compiled: 2021-04-29)
MAIN:  Running one task without MPI parallelization.
MAIN:  Running with just one thread per task.
MAIN:  Lua interpreted linked in.
MAIN: =============================================================
LoadInputFile: Trying to read "Run Control" section only
MAIN: 
MAIN: 
MAIN: -------------------------------------
MAIN: Reading Model: case.sif
LoadInputFile: Scanning input file: case.sif
LoadInputFile: Scanning only size info
LoadInputFile: First time visiting
LoadInputFile: Reading base load of sif file
LoadInputFile: Loading input file: case.sif
LoadInputFile: Reading base load of sif file
Loading user function library: [Electrokinetics]...[helmholtz_smoluchowski2]
Loading user function library: [Electrokinetics]...[helmholtz_smoluchowski1]
LoadInputFile: Number of BCs: 4
LoadInputFile: Number of Body Forces: 0
LoadInputFile: Number of Initial Conditions: 0
LoadInputFile: Number of Materials: 1
LoadInputFile: Number of Equations: 1
LoadInputFile: Number of Solvers: 3
LoadInputFile: Number of Bodies: 1

ElmerAsciiMesh: Base mesh name: ./.
MapCoordinates: Scaling coordinates: 1.000E-05 1.000E-05 1.000E+00
LoadMesh: Elapsed REAL time:     0.0080 (s)
MAIN: -------------------------------------
AddVtuOutputSolverHack: Adding ResultOutputSolver to write VTU output in file: case
OptimizeBandwidth: ---------------------------------------------------------
OptimizeBandwidth: Computing matrix structure for: navier-stokes...done.
OptimizeBandwidth: Half bandwidth without optimization: 89
OptimizeBandwidth: 
OptimizeBandwidth: Bandwidth Optimization ...done.
OptimizeBandwidth: Half bandwidth after optimization: 27
OptimizeBandwidth: ---------------------------------------------------------
ERROR:: CheckLinearSolverOptions: MUMPS solver has not been installed.

STOP 1
```
In the solver setting for **advection diffusion solver**, I check that the method is **iterative CG**, not `MUMPS` .
![image](https://user-images.githubusercontent.com/15122811/117094463-6d934600-ad96-11eb-903d-779dc3bfe2c1.png)

Should I install **MUMPS** and add it to system path?

**Comment by richb2k** [comment]
I downloaded tutorials-GUI-files.zip dated 2021-04-01, and ran the Electrokinetics tutorial without making any changes.

The same error message came up: 

> ERROR:: CheckLinearSolverOptions: MUMPS solver has not been installed.

This tutorial used to work in March of 2021.

In March, I installed Elmergui without MPI.  In mid April, I installed Elmergui with MPI.  That might be related to this issue?

**Comment by richb2k** [comment]
Using Elmer with MPI, another tutorial gives the same error message:

ElasticPlateEigenmodesGUI.

I ran each of the 30+ gui tutorials, only these two tutorials had the error message.

**Comment by richb2k** [comment]
Both tutorials have been revised with PR#21 in elmerfem-manuals.  Looks like maybe changes to ElmerGUI caused these two tutorials to no longer work properly?  It would be nice if there was a way to automatically test the tutorials using ElmerGUI.

**Comment by richb2k** [comment]
The key issue was that with each of the two tutorials, if you just opened each project and immediately looked at Equation 1, Electrostatics, Linear Systems, it called for direct solver MUMPS, instead of calling for direct solver UMFPACK as shown in the tutorial.

**Comment by raback** [comment]
Thanx Kevin. I think the reason was that the order in the GUI was changed from (banded,umfpack,mumps) to (umfpack,mumps,banded) because banded is usually a very bad idea.

**Comment by richb2k** [comment]
That change to the order of the direct solvers makes sense, although it broke the two tutorials.  Not a problem, easy enough to fix.
