### ISSUE TITLE
ElmerGUI does not handle  Output, Timestep intervals and Timestep Sizes arrays

### ISSUE THREAD

**Issue by ealbiter** [ElmerCSC/elmerfem#276]
Some weeks ago, I tried to use variable time steps in a transient simulation, following the suggestions in this [forum post](http://www.elmerfem.org/forum/viewtopic.php?p=5097&sid=f29a652fa6cfec6684a9129fd40c14f9#p5097). However, I realized that ElmerGUI does not take into account the n values entered in these fields since the generated SIF does not contain the correct size of the array, i. e., it does not generate the Output Intervals(n), Timestep Intervals(n) and Timestep Sizes(n) lines correctly. Due to this, ElmerSolver only uses the first value of these fields.
I have located the lines that need to be modified in the SIFgenerator class and [added my proposed changes](https://github.com/ealbiter/elmerfem/commit/29104315b961d12f1189f29ccfe2b18fa9a335f9) to correct this issue. If you wish, I can make a PR for your review. 
By the way, thank you for this excellent software.

**Comment by raback** [comment]
Yes, this would make life easier! Thanx for your effort. Please make a PR. 

Currently you can use the following syntax:
`Timestep Sizes = Size 3; 0.01 0.1 1.0`
The problem is that this is unintuitive and nobody uses this.
