### ISSUE TITLE
Workflow Documentation (Release Management)

### ISSUE THREAD

**Issue by drhooves** [ElmerCSC/elmerfem#28]
Hi, I'm building/maintaining debian packages of elmerfem for a small team where I work. So I'm very interested in release management and so forth, but wasn't able to find any documentation on these topics. 

I understand that there are two main branches: 'devel' and 'release'. 'devel' is where all the new stuff goes. But then, at some point 'devel' and 'release' are merged back and forth serveral times till a release commit gets taged with a version number. Then regular development continues inside the devel branch? Is that right? Or did a missread 'git log'?

**A few questions:**
- When or why is devel merged into release? Is there some grand plan for the next release or some  indicator that devel has stabalized?
- The release cycles are quite long, so I have to build from devel to get the latest fixes. Is the current stable release maintained in some way?

I'll be grateful if someone could clear things up for me.

**Comment by raback** [comment]
Hi, yes you figured the policy quite closely as we do it. As it happens we are releasing 8.1. probably on monday so recently there has been merging between devel and release which is usually static. The devel branch gets small edits directly but for larger modifications we use separate branches, e.g. contact, lumping, parallel-test etc. Only when these separate branches are somewhat mature are they merged with devel. Before doing the merge all tests (currently about 370) must pass. 

So we consider devel stable and fully backwards compatible. The release branch just adds on extra layer of stability which may be needed by some users. There is no grand plan when a snapshot of devel is made a release. Usually it is after concluding that it is about time and there are no major new developments around the corner, and no other deadlines to meet.  

-Peter

**Comment by drhooves** [comment]
Thanks very much for clearing this up. More documentation on organisational topics like that would definitly benefit a project of that size.

-Markus
