### ISSUE TITLE
Unable to compile elmerfem

### ISSUE THREAD

**Issue by gianlucapettinello** [ElmerCSC/elmerfem#285]
While compiling elmerfem I get a weird error on src/matc/str.c row 85.
sprintf(..., fmt) gives a compile error that format is not literal.
The library is pretty old. Is anybody getting the same error?

**Comment by gianlucapettinello** [comment]
To be more precise here is the error:

/home/gianluca/builds/elmerfem/src/elmerfem-release-9.0/matc/src/str.c:85:5: error: format not a string literal and no format arguments [-Werror=format-security]
   85 |     sprintf(str_pstr, fmt);
      |     ^~~~~~~
cc1: some warnings being treated as errors
make[2]: *** [matc/src/CMakeFiles/matc.dir/build.make:328: matc/src/CMakeFiles/matc.dir/str.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:14490: matc/src/CMakeFiles/matc.dir/all] Error 2
make: *** [Makefile:166: all] Error 2

**Comment by juharu** [comment]
Hi 
>/home/gianluca/builds/elmerfem/src/elmerfem-release-9.0/matc/src/str.c:85:5: error: format not a string literal and no format arguments [-Werror=format-security] 

Somehow you seem to have enabled "-Wformat" and "-Werror=format-security", the former enabling format string checking, and the latter turning warnings 
to fatal errors within gcc. Even the latest gcc development version doesn't  seem to do that by default ? Maybe some generic setting includes this like  "-Wpedantic" or some such ? 

Br, Juha

**Comment by gianlucapettinello** [comment]
Thanks, changed config in makepkg.conf and it worked!
