### ISSUE TITLE
Remove autom4te.cache

### ISSUE THREAD

**Issue by drhooves** [ElmerCSC/elmerfem#29]
Followoing folders shouldn't be in a git repository or release tarball:

```
elmergrid/autom4te.cache/
fem/autom4te.cache/
front/autom4te.cache/
mathlibs/autom4te.cache/
meshgen2d/autom4te.cache/
post/autom4te.cache/
umfpack/autom4te.cache/
```

I believe cmake doesn't use them anyway...

**Comment by raback** [comment]
Thanx for reporting. We are in the process of cleaning the repo from old stuff. There is already a RemoveObsolite branch and after some testing we will merge this with the devel.
