### ISSUE TITLE
Fail to build with Qwt 6.2

### ISSUE THREAD

**Issue by ealbiter** [ElmerCSC/elmerfem#293]
Qwt was recently updated to v6.2 in my system. With this version, ElmerGUI fails to compile due to the qw_compat.h file was [removed](https://qwt.sourceforge.io/qwtchangelog.html).
I have already made the changes to resolve the problem. I tested the fix with Qwt 6.1.6 and 6.2.0, and the code compiles fine with both versions. In a short time, I will make a PR for your review.

**Comment by raback** [comment]
Thanx! Just merged.

**Comment by ealbiter** [comment]
Happy to help. Closing issue.
