### ISSUE TITLE
Suggestion to Migrate to QT5

### ISSUE THREAD

**Issue by spit4520** [ElmerCSC/elmerfem#296]
Hello,

The build chain on Ubuntu 20.04 is very difficult to source/maintain. Ubuntu 22.04 is right around the corner and it will be equally as difficult if not harder. libqt4 and libwqt are no longer packaged directly for ubuntu, there are different ppa's you can get them from, but they also have a litany of broken dependencies. My polite suggestion would be to begin the migration to a more modernized and maintained version of the tool kit.

I originally looked at building the program myself because I didn't realized that there was a "eg" version of the package from the main "elmer" website. (I also suggest you add a second line in the download scripts on the site to let people know they can download the graphical version) Most of my engineers are EE's and aren't Linux wizards so the graphical version of the tool is a lot more helpful for them.

If there are compatibility reasons for not moving to QT5, they should be highlighted at the top of the readme and put on the kaban board so people can submit PR's to fix it. This tool appears to be exceedingly important (especially in the age of the IoT) I can only imagine that more people would like to help prop this tool up over the $30,000 tools from Cadence and the like

Thanks

**Comment by gianlucapettinello** [comment]
+1
qt4 in very obsolete

**Comment by raback** [comment]
We would of course be happy to stay tuned with library developments. Unfortunately the current Elmer team lacks some skills here so whereas we can pretty quickly write a new PDE solver, managing the different builds may be trickier. But indeed we should follow what is happening at the Ubuntu packages. We are also happy to take contributions from build wizards!

**Comment by barracuda156** [comment]
It is very much desirable to keep compatibility with Qt4. Sure enough, Qt5 may be added as well. But please keep Qt4.

**Comment by barracuda156** [comment]
> If there are compatibility reasons for not moving to QT5, they should be highlighted at the top of the readme and put on the kaban board so people can submit PR's to fix it.

@spit4520 Qt5 is not universally supported. Fixing it is likely non-trivial and time-consuming. Far easier just to retain fallback code with Qt4 compatibility.
