### ISSUE TITLE
Compile on Mac OS Monterey12.1 (Mac Mini M1)

### ISSUE THREAD

**Issue by ouening** [ElmerCSC/elmerfem#313]
**OS: Mac OS Monterey 12.1
Computer: Mac mini (M1, 2020)**
elmerfem version: 9.0 (devel 7665920e)
## 1. Prepare
Install gcc, g++, gfortran, cmake, Qt5 and qwt-qt5:

`brew install gcc g++ gfortran cmake qt@5 qwt-qt5`

The `gcc` and `g++` installed from `brew` are located in `/opt/homebrew/bin/gcc-11` and `/opt/homebrew/bin/g++-11`.
`gfortran` is located in `/opt/homebrew/bin/gfortran`.

We can use command: 

```
brew info qt@5
brew info qwt-qt5
```

to see where the `qt5` and `qwt-qt5` are installed (my computer is m1 mac mini, the installation dir is in `/opt`). 

And command: `find /opt -name Qt5Config.cmake` to find `Qt5_DIR`

Same as `qwt-qt5`. Be aware we should install `qt@5` instead of `qt`, so as `qwt-qt5` instead of `qwt`. See https://formulae.brew.sh/formula/qt@5 and https://formulae.brew.sh/formula/qwt-qt5#default.

## 2. Modify `elmerfem/CmakeLists.txt`
Modify the Apple section configuration:
```cmake
if(APPLE)
  # message("you need to have gcc-gfrotran installed using HomeBrew")
  # set(CMAKE_C_COMPILER "/usr/bin/gcc")
  # set(CMAKE_CXX_COMPILER "/usr/bin/g++")
  set(CMAKE_C_COMPILER "/opt/homebrew/bin/gcc-11")
  set(CMAKE_CXX_COMPILER "/opt/homebrew/bin/g++-11")
  set(CMAKE_Fortran_COMPILER "/opt/homebrew/bin/gfortran")
  # set(BLA_VENDOR "OpenBLAS")
  # option(HUNTER_ENABLED "Enable Hunter package manager support" OFF)
  # set (CMAKE_GENERATOR "Unix Makefiles" CACHE INTERNAL "" FORCE)
  # set(CMAKE_TRY_COMPILE_TARGET_TYPE "STATIC_LIBRARY")
  set(Qt5_DIR "/opt/homebrew/Cellar/qt@5/5.15.2_1/lib/cmake/Qt5")
  set(QWT_INCLUDE_DIR "/opt/homebrew/opt/qwt-qt5/include")
  set(QWT_INCLUDE_DIR "/opt/homebrew/Cellar/qwt-qt5/6.2.0/lib/qwt.framework/Versions/6/Headers")
  set(QWT_LIBRARY "/opt/homebrew/opt/qwt-qt5/lib/qwt.framework/qwt")
endif()
```
and
```cmake
IF(APPLE)
  SET(CMAKE_MACOSX_RPATH 1) 
    # on OSX FindOpenGL uses framework version of OpenGL, but we need X11 version
    # FIND_PATH(GLX_INCLUDE_DIR GL/glx.h
    #   PATHS /opt/X11/include /usr/X11/include /usr/X11R6/include)
    # find_library(X11_GL_LIB GL
    #   PATH /opt/X11/lib /usr/X11/lib /usr/X11R6/lib)
  FIND_LIBRARY(OPENGL_gl_LIBRARY GL
        PATHS /opt/X11/lib /usr/X11/lib /usr/X11R6/lib)
  FIND_LIBRARY(OPENGL_glu_LIBRARY GLU
        PATHS /opt/X11/lib /usr/X11/lib /usr/X11R6/lib)
  LIST(APPEND LIBS ${OPENGL_gl_LIBRARY})
# INCLUDE_DIRECTORIES(${GLX_INCLUDE_DIR})
ENDIF()
```
## Compile and install
Just `make -j6 && sudo make install`

**Comment by ShamoX** [comment]
Hello, thanks for the work.

This solution may have worked before gcc 12 release, but we need now to precise gcc@11 when installing.

I also made more flexible the variable (to prevent incompatibility to old intel macs).

I made a PR: #393.

**Comment by AkthemRehab** [comment]
Hello, thank you for this. It helped me install elmerfem on my mac m2. However when I try to follow the video in [https://www.youtube.com/watch?v=h7PswPM9qtk] Errors are returned and I am not able to continue the installation. Specifically, when I run: 

`
cmake -DWITH_ELMERGUI:BOOL=TRUE -DWITH_MPI:BOOL=TRUE -DWITH_LUA:BOOL=TRUE -DWITH_Mumps:BOOL=TRUE -DMUMPSROOT=../mumps -DCMAKE_INSTALL_PREFIX=../install ../elmerfem 

`
I get the following: 

```
-- Finding Mumps
CMake Error at cmake/Modules/FindMumps.cmake:149 (MESSAGE):
  Mumps library not found.
Call Stack (most recent call first):
  CMakeLists.txt:536 (FIND_PACKAGE)
```
I installed mumps as per the video but the error is persisting.

i tried many times with my limited mac/shell experience. Hope you can help resolving this.

**Comment by bdlabitt** [comment]
Any ideas on how to update to Ventura on an M3?  gcc is at 13 now.  Are the opengl lib paths the same?

**Comment by bdlabitt** [comment]
There's no utility find_program as used in CmakeLists.txt.  This documentation is very outdated.

**Comment by nega0** [comment]
`find_program` is a CMake command. It's not an external utility.

**Comment by bdlabitt** [comment]
> Any ideas on how to update to Ventura on an M3? gcc is at 13 now. Are the opengl lib paths the same?

That's my real question.  There's no /opt/X11 in Ventura, but there is /opt/homebrew/opt/X11 which is a simlink which leads to some strange files.  But in /opt/homebrew/opt the following files exist

<img width="251" alt="Screenshot 2024-02-05 at 3 59 38 PM" src="https://github.com/ElmerCSC/elmerfem/assets/26691788/e109d0a2-2748-4090-b736-4dcd21d2fd1f">

**Comment by tyVandeZande** [comment]
MacBook Pro  M1
Sonoma 14.3.1

I followed the original instructions outlined by @ouening and it sent me into an infinite install loop.

**Comment by raback** [comment]
I am closing some old build related issues since most likely they are not relevant any more.

**Comment by jaydeshpande** [comment]
https://github.com/ElmerCSC/elmerfem/issues/503#issuecomment-2719224234
