### ISSUE TITLE
Install on ubuntu jammy : apt update -> 404  Not Found

### ISSUE THREAD

**Issue by nathmo** [ElmerCSC/elmerfem#328]
Hi,
I tried to install on ubuntu 22.04  (jammy) but when I try to run the following command : 
`$ sudo apt-add-repository ppa:elmer-csc-ubuntu/elmer-csc-ppa`
`$ sudo apt-get update`
`$ sudo apt-get install elmerfem-csc`
I get 
`
Ign :5 https://ppa.launchpadcontent.net/elmer-csc-ubuntu/elmer-csc-ppa/ubuntu jammy InRelease
Err :6 https://ppa.launchpadcontent.net/elmer-csc-ubuntu/elmer-csc-ppa/ubuntu jammy Release  404  Not Found [IP : 2001:67c:1560:8008::19 443]
`

Since the package don't seem to have been released for jammy yet, I tried to patch "/etc/apt/sources.list.d/elmer-csc-ubuntu-ubuntu-elmer-csc-ppa-jammy.list" with focal instead of jammy but as you might have guessed I am greeted with a bunch of dependencies that can't be met. :

``` Certains paquets ne peuvent être installés. Ceci peut signifier
que vous avez demandé l'impossible, ou bien, si vous utilisez
la distribution unstable, que certains paquets n'ont pas encore
été créés ou ne sont pas sortis d'Incoming.
L'information suivante devrait vous aider à résoudre la situation : 

Les paquets suivants contiennent des dépendances non satisfaites :
 elmerfem-csc : Dépend: libmumps-5.2.1 mais il n'est pas installable
E: Impossible de corriger les problèmes, des paquets défectueux sont en mode « garder en l'état ».
```

(sorry the error message are in french)

Do you have an idea when it will be available for Ubuntu 22.04 ? 
is there any way to help to package it for Ubuntu 22.04 ?

**Comment by nathmo** [comment]
It might bite me in the ... later but i managed to make it work by : 
1) sudo nano /etc/apt/sources.list.d/elmer-csc-ubuntu-ubuntu-elmer-csc-ppa-jammy.list
i replaced jammy by focal
2) sudo apt update
3) download the missing library from any mirror listed here https://packages.ubuntu.com/focal/amd64/libmumps-5.2.1/download and install it
4) sudo apt-get install elmerfem-csc
5) ElmerGUI

**Comment by zackwhit** [comment]
A release for 22.04 would be great! I'm also struggling to get it installed. I elected to modify the dependencies to allow the most recent versions of libmumps and (in the case of the groovy version) libhypre. I have done zero testing to see what kind of problems that might create, but the GUI does open at the very least. (Gotta run ElmerGUI in the terminal, doesn't seem to show up in start menu). 

I also tried to install from source, but ran into a a "internal compiler error". This is after I installed a couple packages to make cmake more happy (I think primarily qtscript5-dev). I can't made heads or tails of the error and so have no idea how to deal with it. Maybe the F95 compiler being used is tripping on the F90 files? No idea.

```
[ 64%] Building Fortran object fem/src/modules/CMakeFiles/StatElecSolve.dir/StatElecSolve.F90.o  
during GIMPLE pass: omplower                                                                     
/home/gector/git/elmerfem/fem/src/modules/StatElecSolve.F90:582:67:                              
                                                                                                 
  582 |        !$omp                  bf_id, gotIt, Var, TID) default(none)                      
      |                                                                   ^                      
internal compiler error: in gfc_omp_clause_default_ctor, at fortran/trans-openmp.c:646           
0x7f2d339abd8f __libc_start_call_main                                                            
        ../sysdeps/nptl/libc_start_call_main.h:58                                                
0x7f2d339abe3f __libc_start_main_impl                                                            
        ../csu/libc-start.c:392                                                                  
Please submit a full bug report,   
 ```
 
 Edit: I also had to `ln libmumps_common-5.4.0.so libdmumps-5.2.1.so` to make elmerfem use the right library. That seemed to work, but I eventually just installed the proper version anyway.

**Comment by Black-Drag0n** [comment]
Trying to build on MacOS 13.1 I am encountering the same issue @zackwhit posted

`internal compiler error: in gfc_omp_clause_default_ctor, at fortran/trans-openmp.cc:704
Please submit a full bug report, with preprocessed source (by using -freport-bug).
See <https://github.com/Homebrew/homebrew-core/issues> for instructions.
make[2]: *** [fem/src/modules/CMakeFiles/StatElecSolve.dir/StatElecSolve.F90.o] Error 1
make[1]: *** [fem/src/modules/CMakeFiles/StatElecSolve.dir/all] Error 2
make: *** [all] Error 2`

Any ideas on how to resolve this

**Comment by raback** [comment]
There is currently a (not fully complete) jammy installer.
