### ISSUE TITLE
Segfault for empty mesh partition (from Zoltan)

### ISSUE THREAD

**Issue by marcel-dcs** [ElmerCSC/elmerfem#329]
For some simulations on 32 processors (it did not happen for less processors) we have encountered a segfault during the automatic Zoltan partitioning of the mesh. I tracked it down to the following piece of code:

https://github.com/ElmerCSC/elmerfem/blob/b502b99a5aa45158971da089546edd91b77f6fbd/fem/src/MeshUtils.F90#L3195-L3201
which gives a segfault if one (or more) parallel mesh partition(s) (as determined by Zoltan) are empty. 

As other people might encounter the same issue, here a simple fix. I managed to prevent this from happening by wrapping the loop with:

```
IF( Mesh % NumberOfNodes > 0 ) THEN
...
END IF
```

**Comment by raback** [comment]
Ok, fixed with essentially your suggestion. Thanx for reporting!
