### ISSUE TITLE
Avoid writing netgen.prof file to disk

### ISSUE THREAD

**Issue by drws** [ElmerCSC/elmerfem#330]
Elmer FEM is currently writing the `netgen.prof` file [many times](https://github.com/ElmerCSC/elmerfem/blob/aaa6c4a345c73ba248c475d27975c5e3a9fa7758/ElmerGUI/netgen/libsrc/general/profiler.cpp#L44-L53), even if it is only started and closed. The problem is the location of the file, home folder in my case. Besides annoying the user, this file seems runtime-related and it is probably unnecessarily written to disk, producing additional write cycles. If the data is important to be kept in a file, some temporary location such as `/tmp` would probably be more appropriate.

**Comment by raback** [comment]
The writing is now by default skipped. See commit: b6cc90dab703de4ee5a1563f100495b6968d1135

Thanx for the idea!
