### ISSUE TITLE
Incorrect library order in fem/src/CMakeLists.txt

### ISSUE THREAD

**Issue by Azrael3000** [ElmerCSC/elmerfem#331]
https://github.com/ElmerCSC/elmerfem/blob/f511fdd690999d5d066d76684d19cb3d0626dcae/fem/src/CMakeLists.txt#L180

should be

```
${LAPACK_LIBRARIES}  ${BLAS_LIBRARIES} 
```

If you are linking with static lapack and blas, lapack must preceed blas in the linking stage otherwise the blas symbols won't be included in the libelmersolver.so library.

**Comment by raback** [comment]
This is now changed according to your suggestion.
