### ISSUE TITLE
Support mesh folders with spaces

### ISSUE THREAD

**Issue by nikosavola** [ElmerCSC/elmerfem#356]
It seems mesh directories with spaces are not currently supported for ElmerSolver, for example
```
Header
    Mesh DB "." "my mesh"
End
```
I saw one post [in the forums](http://elmerfem.org/forum/viewtopic.php?t=7259) about this as well.

ElmerGrid appears to be fine with spaces at least with my testing, but it of course cannot be fully utilised w/o support in ElmerSolver.

**Comment by raback** [comment]
This goes rather deep in the parsing since space is used as a separator and and also the Mesh DB is parsed with the same routines. What could be done is to treat file related names differently, or at least warn about the directory/file name being risky.

**Comment by jvencels** [comment]
This is relevant for Windows users and something that bothers me as well.

**Comment by raback** [comment]
Did you have time to test whether this minor fix works?

**Comment by jvencels** [comment]
For case with folder name that has spaces = C:\Users\juris\Desktop\name with spaces"
```
MAIN: ElmerSolver finite element software, Welcome! 
MAIN: This program is free software licensed under (L)GPL 
MAIN: Copyright 1st April 1995 - , CSC - IT Center for Science Ltd. 
MAIN: Webpage http://www.csc.fi/elmer, Email elmeradm@csc.fi 
MAIN: Version: 9.0 (Rev: Release, Compiled: 2022-10-26) 
MAIN:  Running in parallel using 12 tasks. 
MAIN:  Running with just one thread per task. 
MAIN:  Lua interpreter linked in.
MAIN:  External optimization routines linked in. 
MAIN: ============================================================= 
ERROR:: ElmerSolver: Unable to find input file [C:\Users\juris\Desktop\name], can not execute. 
ERROR:: ElmerSolver: Unable to find input file [C:\Users\juris\Desktop\name], can not execute.
```
Different scenario = C:\Users\juris\Desktop\name with spaces\case", but identical error.
```
ERROR:: ElmerSolver: Unable to find input file [C:\Users\juris\Desktop\name], can not execute.
```

**Comment by raback** [comment]
And here your "Mesh DB" line looks like?

**Comment by jvencels** [comment]
Mesh folder is called mesh
```
INCLUDE mesh/mesh.names
Header
  CHECK KEYWORDS Warn
  Mesh DB "." "mesh"
  Include Path ""
  Results Directory "results"
End
```

**Comment by raback** [comment]
Ok. I think these are different issues. The minor fix enables things like: Mesh DB "." "mesh with space". I tested under Linux and I there is no problem to run "ElmerSolver ~/test dir/case.sif". How do you call the simulation here?

**Comment by juharu** [comment]
Hi 

On my laptop running Debian Linux, current directory doesn't seem to get prepended to the name 
(to my knowledge ElmerSolver does not try to do anything like this?), so with 

Mesh DB "." "mesh with spaces" 

and 

cd "name with spaces" 
ElmerSolver 

is just fine (after the small fix by Peter). 

What does not work, however, are things like 'Mesh DB "path with spaces" "mesh"', 
but these would be a bit rare anyway ? This we could enable by requiring some marker 
to end the path (f.ex. "/"), if the path contains spaces. 

Anyway, don't quite understand why all this would behave differently on Windows ? 

Br, Juha

**Comment by jvencels** [comment]
Thanks, Peter and Juha. My problem was that I had run Elmer through a python script using a subprocess and giving it the full path to the case file.
When running Elmer from the directory or putting paths within "quotes" , it works just fine.

**Comment by raback** [comment]
Ok, I close the issue.
