### ISSUE TITLE
Windows binaries haven't built in a while

### ISSUE THREAD

**Issue by richb2k** [ElmerCSC/elmerfem#369]
The Windows binaries haven't built properly in several weeks.  Perhaps someone could take a look at what is going on with the built process?

Thanks,  Rich.

**Comment by raback** [comment]
Hi Rich, Thanx for the notice. I just cleaned up things and the VM is back to work. There are fresh binaries at nic.funet.fi. -Peter

**Comment by richb2k** [comment]
Thank you!
