### ISSUE TITLE
MacOS 13.1 StatElecSolve breaks compiler

### ISSUE THREAD

**Issue by Black-Drag0n** [ElmerCSC/elmerfem#373]
StatElecSolve.F90: 

`!    CONTAINS

! !------------------------------------------------------------------------------
!      SUBROUTINE BulkAssembly()
!        !------------------------------------------------------------------------------
!        !$omp parallel shared(Solver, Model, dim, at0, &
!        !$omp                 PermittivityOfVacuum, Message) &
!        !$omp          private(t, CurrentElement, i, j, k, n, ntot, NodeIndexes, &
!        !$omp                  bf_id, gotIt, Var, TID) default(none)`

results in the following error

`internal compiler error: in gfc_omp_clause_default_ctor, at fortran/trans-openmp.cc:704`

Among the other things I had to modify to get this to build with the GUI I ended up completely commenting out this entire file. I believe the issue has to do with trying to parse nested subroutines but beyond that I am fairly stumped.

I started with gcc-12, and went all the way back to gcc-6 but the result was always the same.

Otherwise I have a branch that I could make available that will successfully build with mpi and gui using qt5

**Comment by juharu** [comment]
Hi 

Thanks for reporting, and sorry for the slow response. 
I disabled the OpenMP related pragmas from StatElecSolve.F90 "BulkAssembly()" subroutine. 
This seemed to prevent the gcc compiler from crashing. Let's wait for someone to fix 
gcc-openmp-compilation before re-enabling, I guess. 

Commited to github 'devel'. 

Br, Juha

**Comment by juharu** [comment]
Hi
Just for the heck of it, I slightly modified the StatElecSolve.F90 code such that  "gcc -fopenmp" seemed
happier than before. I even tried with a few different gcc-versions. Anyway, maybe you could give it  a try
too ?
The modified version is now on github elmerfem 'devel'.
-Juha
