### ISSUE TITLE
Elmer and ParaView take five minutes each to open.

### ISSUE THREAD

**Issue by mistergitj** [ElmerCSC/elmerfem#380]
I DLed and installed Elmer and ParaView as a nightly build 29 Jan 2023. Opening Elmer the GUI takes five minutes and then opening ParaView from the GUI takes another 5 minutes. This appears the same symptom as SDRangel (Software Defined Radio application) after I had updated W10 to 22H2. This cleared up suddenly after a few weeks and SDRangel is working fine. I suspect a W10 update of this good happening. Thanks and enjoy, John.
PS: I also opened a bug report in the Forum but got no response. New here and do not know what to use to report problems.
Top

**Comment by richb2k** [comment]
Hello,  IMHO the forum is the best place to report windows type problems.  Please continue the discussion in the forum and if you agree, maybe close this issue?   Rich.

**Comment by mistergitj** [comment]
Thanks, rich2k. Closing this issue. John.

**Comment by mistergitj** [comment]
Wrong forum for Windows problems.

**Comment by mistergitj** [comment]
Rich_B, I went to the forum to reply to your suggestion, but was unable to login. I have closed the Issue on GitHub.John.

    On Tuesday, January 31, 2023 at 04:30:38 PM CST, Rich_B ***@***.***> wrote:  
 
 


Hello, IMHO the forum is the best place to report windows type problems. Please continue the discussion in the forum and if you agree, maybe close this issue? Rich.

**Comment by richb2k** [comment]
Hello John,  sorry to send you on a chase.  Forum login issues happen, and I can't do anything to help with login.  I guess in the meantime, feel free to add comments to this discussion, even though it's closed.  Are you still having the same issue with time delay upon opening?

Rich.

**Comment by mistergitj** [comment]
Yes, the issues continue (right at 5 minutes). I had a similar login issue with another PHPBB. I thought I had an idea to corner the delay but it did not pan out. Thanks much, John.

    On Wednesday, February 1, 2023 at 03:44:59 PM CST, Rich_B ***@***.***> wrote:  
 
 


Hello John, sorry to send you on a chase. Forum login issues happen, and I can't do anything to help with login. I guess in the meantime, feel free to add comments to this discussion, even though it's closed. Are you still having the same issue with time delay upon opening?

Rich.

**Comment by richb2k** [comment]
1.  Are you running any anti-virus software, other than what is built into Windows 10? 
2.  If you open Task Manager and sort processes by 'Disk', and then open ElmerGUI, do any other processes show up as using the Disk? 

Rich.

**Comment by mistergitj** [comment]
Thanks Rich_B, I use Comodo AV/FW and have considered turning it off for a test. There is no significant disk activity. An SDRangle developer built a special binary with logging to see what was going on and it just showed an almost 5 minute stoppage in any activity that made no sense to him. Using Process Lasso shows the PID doing nothing for 5 minutes. I suspect something, QT, is to blame but the SDRangle developer dose not. I am looking to an upgrade to QT 6.5 which is targeted to W10 22H2. They are currently on 5.15.2. Thanks and enjoy, John.

    On Thursday, February 2, 2023 at 08:08:37 AM CST, Rich_B ***@***.***> wrote:  
 
 

   
   - Are you running any anti-virus software, other than what is built into Windows 10?
   - If you open Task Manager and sort processes by 'Disk', and then open ElmerGUI, do any other processes show up as using the Disk?

Rich.

**Comment by richb2k** [comment]
Hello again,

I should have asked this earlier, did you download and install Elmer following the steps shown in GetStartedElmer.pdf?

Second, if that method has the delay issue, maybe try using one of the zip files from [https://www.nic.funet.fi/pub/sci/physics/elmer/bin/windows/](url) to create a portable installation?  Follow the steps shown in this forum post, which shows how to set the environment variables needed for a portable installation:
[http://www.elmerfem.org/forum/viewtopic.php?t=7817](url)

Thanks,  Rich.

**Comment by mistergitj** [comment]
Thanks again, Rich. I am going to abandon Elmer to concentrate on openEMS which I have running. Octave cannot find QT5 so have yet to see if 5 minute delay is present. Thanks much for your response. Enjoy, John.

**Comment by raback** [comment]
It is difficult to know what one could do within Elmer here to fix this problem. If it also concerns Paraview then it is not really Elmer. OpenEMS is FDTD code so probably it has quite different feature set.

**Comment by mistergitj** [comment]
Thanks, raback. I am not blaming Elmer, obviously I do not know what is going on. This is maybe the third really good application that has been ported from Linux to Windows that I had tried in the last few months that have problems that remain unfixed. One other app had this same 5 minute (almost exactly 5 minutes) delay that just mysteriously disappeared one day with no changes. Perhaps a W10 update. OpenEMS works well but cannot find QT which is installed. So some of the features fail to work. Today it surprisingly threw up a new set of errors and another three plots quit appearing. I really appreciate these applications and the time and effort spent on them. I just need to move on. Thanks and enjoy, John.

**Comment by richb2k** [comment]
Hello John,

What happened when you turned off the Comodo anti-virus software?  Or, better yet, perform a Clean Boot or start in Safe Mode and then try to start ElmerGUI?   Don't leave us hanging!

Rich.

**Comment by mistergitj** [comment]
I am sorry, Rich. I do not wish to abandon you but I believe I am beating a dead horse. I found this some time ago and wondered what it really means:
<img width="572" alt="QT_22H2" src="https://user-images.githubusercontent.com/45215756/217276405-7924f37c-4465-4dfb-97f0-380cc1f87889.png">
I am running 22H2 on W10 and intend to upgrade to W11 soon. I am also out of my personal resources. I may run into this same problem with openEMS (connection to Octave is broken) when I finally get it connected. I would consider given Elmer another try when the appropriate version of QT is released. Thanks for all your help. Enjoy, John.
