### ISSUE TITLE
ElmerGUI generates incorrect SIF for linear materials with Rayleigh damping

### ISSUE THREAD

**Issue by Partmedia** [ElmerCSC/elmerfem#387]
ElmerGUI generates an incorrect SIF for linear materials with Rayleigh damping.

Reproduced in a recent `devel` branch (f59f3a2135).

## Steps to Reproduce
Specify some numbers in the materials tab:

![image](https://user-images.githubusercontent.com/3229565/221667604-d98c0c79-2ffa-4bd5-81f0-59cd5347a822.png)

Then generate and view SIF (Sif → Generate, Sif → Edit):

```
Material 1
  Name = "Ruthenium"
  Rayleigh alpha = 1e-10
  Heat Conductivity = 237.0
  Sound speed = 5000.0
  Rayleigh beta = 2e-10
  Density = 13420
  Poisson ratio = 0.3
  Youngs modulus = 402.5e9
  Rayleigh Damping = True
End
```

Which results in the following error when running ElmerSolver:
```
LoadInputFile: Reading base load of sif file
ERROR:: LoadInputFile: 
ERROR:: LoadInputFile:  Unknown specifier: [1e-10]
ERROR:: LoadInputFile:  In section: [material 1]
ERROR:: LoadInputFile:  For property name:[rayleigh alpha]
STOP 1
```

I corrected the SIF by hand (changes in double stars `** **`), which results in a SIF that runs:
```
Material 1
  Name = "Ruthenium"
  Rayleigh **Damping Alpha** = 1e-10
  Heat Conductivity = 237.0
  Sound speed = 5000.0
  Rayleigh **Damping Beta** = 2e-10
  Density = 13420
  Poisson ratio = 0.3
  Youngs modulus = 402.5e9
  Rayleigh Damping = **Logical** True
End
```

**Comment by raback** [comment]
Just accepted the PR. Thanx Rich for fixing and Partmedia for reporting!
