### ISSUE TITLE
r_component is by localC larger than it should be

### ISSUE THREAD

**Issue by jvencels** [ElmerCSC/elmerfem#392]
Hi @juharu,
There were changes a month ago that affected circuit outputs.

The source is fem/src/modules/CircuitsAndDynamics.F90. Coil conductance is not being multiplied by local conductivity:
https://github.com/ElmerCSC/elmerfem/commit/2373af0e6bf051ab49f97be759391a64a9d4374b#r108302956

**Comment by juharu** [comment]
Hi Juris 

Thanks for looking into this! 

Could you be a bit more specfic, where do you see the problem exactly (code and / or a test case ? ), 
harmonic vs transient ? 
For example, the code shows changes like 

cmplx_val = IP % s(t) * detJ * localC * SUM (gradv * Wbasis(j,:)) * Comp % VoltageFactor 
cmplx_val = IP % s(t) * detJ * SUM (gradv * Wbasis(j,:)) * Comp % VoltageFactor 
END IF 
END IF 


IF ( .NOT. SkinBc) cmplx_val = cmplx_val * localC + im * Omega * cmplx_val * localP 


E.g. the last line multiplies by "localC" removed from the line above ? Can't directly see the trouble, 
there are a lot of changes tough, so probably I'm missing something... 

Thanks! 

br, Juha 



From: "Juris Vencels" ***@***.***> 
To: "ElmerCSC" ***@***.***> 
Cc: "juharu" ***@***.***>, "Mention" ***@***.***> 
Sent: Monday, 10 April, 2023 17:26:36 
Subject: [ElmerCSC/elmerfem] r_component is by localC larger than it should be (Issue #392) 





Hi [ https://github.com/juharu | @juharu ] , 
There were changes a month ago that affected circuit outputs. 

The source is fem/src/modules/CircuitsAndDynamics.F90. Coil conductance is not being multiplied by local conductivity: 
[ https://github.com/ElmerCSC/elmerfem/commit/2373af0e6bf051ab49f97be759391a64a9d4374b#r108302956 | 2373af0#r108302956 ]

**Comment by jvencels** [comment]
Hi Juha,

The test case with massive coils attached. The issue seems to be present for massive coils only.

See /1962/dat/1962.dat.csv, r_component(1).
The value we obtain with the older Elmer version is 4.86E-006. With the current version, we get 149.

[circuits_harmonic_massive.zip](https://github.com/ElmerCSC/elmerfem/files/11197926/circuits_harmonic_massive.zip)

**Comment by juharu** [comment]
Thanks, 

fix in "devel" ?
