### ISSUE TITLE
problem to compile 

### ISSUE THREAD

**Issue by CristianEta** [ElmerCSC/elmerfem#399]
hello.

First of all, thank you for all your work.

I have problems trying to compile from the source. Its an error with cnaitr.f.

Error: Rank mismatch between actual argument at (1) and actual argument at (2) (scalar and rank-1)
/home/cristian/elmer/elmerfem/mathlibs/src/arpack/cnaitr.f:666:35:

  383 |             call svout (logfil, 1, rnorm, ndigit,
      |                                   2
......
  666 |             call svout (logfil, 2, rtemp, ndigit,
      |                                   1
Error: Rank mismatch between actual argument at (1) and actual argument at (2) (scalar and rank-1)
/home/cristian/elmer/elmerfem/mathlibs/src/arpack/cnaitr.f:737:39:

  383 |             call svout (logfil, 1, rnorm, ndigit,
      |                                   2    
......
  737 |                 call svout (logfil, 2, rtemp, ndigit,
      |                                       1
Error: Rank mismatch between actual argument at (1) and actual argument at (2) (scalar and rank-1)

Its compiled in debian 11 and the parameters of cmake are:
cmake -DWITH_QT5=TRUE -DWITH_ELMERGUI:BOOL=TRUE -DWITH_MPI:BOOL=TRUE -DWITH_Mumps:BOOL=TRUE -DWITH_LUA:BOOL=TRUE -DCMAKE_INSTALL_PREFIX=../install ../elmerfem

can you say me if is a problem with the code or its mine?.

Regards from Chile.

**Comment by richb2k** [comment]
Using the latest commit from github, I'm getting the same error.

Windows 10, without mpi, without mumps, with elmergui

Last time I compiled Elmer was about a month ago, without any errors.

Rich.

**Comment by richb2k** [comment]
Using a commit from 2 days ago, the error occurs. (5/25/2023 3:54:25 AM)
Using a commit from 5 days ago, the error does not occur. (5/22/2023 4:16:09 AM)

**Comment by juharu** [comment]
The fortran compilation is missing the option:

-fallow-argument-mismatch

Probably my fault. You could add this manually or wait for updated Cmake files...
Sorry for the trouble...

**Comment by juharu** [comment]
>>-fallow-argument-mismatch
should be fixed now. Maybe someone could verify and we can close this issue ?

**Comment by CristianEta** [comment]
I compile it again. This time works perfectly.
If i get  other bugs i will comment again.
thanks.

**Comment by richb2k** [comment]
Elmer compiled as usual again, using the latest commit.

Thanks, Rich.

**Comment by juharu** [comment]
Thanks everybody!
