### ISSUE TITLE
ctest crash

### ISSUE THREAD

**Issue by bonze82** [ElmerCSC/elmerfem#419]
WinkelPoissonMetisKwayDual_np8 is causing ctest to crash and also crashes x11 on debian systems.

quad core intel chip with 8 gig of ram.
debian bookworm fully updated.

**Comment by tzwinger** [comment]
Could it be that you are running openmpi and it by default wouldn't allow you to engage more tasks than your physically installed cores (i.e., 4)? The failure of other parallel tests exceeding 4 tasks would confirm this. You can limit the maximum task-count with the variable MPI_TEST_MAXPROC in your cmake command. Easy check if limit applies is to do a `mpirun -np 8 echo "hello world"` in the shell
