### ISSUE TITLE
Elmer VM missing ElmerGUI

### ISSUE THREAD

**Issue by greyltc** [ElmerCSC/elmerfem#426]
Hi. Sorry if this is the wrong place to post this, I can't find a repo that obviously has the VM generation scripts.

I think this is the place for the official elmer VM: https://www.nic.funet.fi/pub/sci/physics/elmer/bin/VirtualMachines/

There's an open virtual appliance file posted there right now called Elmer-Fedora37.ova and the VM that makes doesn't actually have ElmerGUI in it. Is that intentional?

```bash
[elmeruser@fedora bin]$ pwd
/opt/elmer/Elmer_devel/bin
[elmeruser@fedora bin]$ ls -alh
total 7.4M
drwxr-xr-x. 1 elmeruser elmeruser  160 Sep 26 20:46 .
drwxr-xr-x. 1 elmeruser elmeruser   22 Jan  2  2023 ..
-rwxr-xr-x. 1 elmeruser elmeruser 2.3K Sep 26 20:41 elmerf90
-rwxr-xr-x. 1 elmeruser elmeruser 2.3M Sep 26 20:42 ElmerGrid
-rwxr-xr-x. 1 elmeruser elmeruser  530 Sep 26 20:41 elmerld
lrwxrwxrwx. 1 elmeruser elmeruser   15 Jan  2  2023 ElmerSolver -> ElmerSolver_mpi
-rwxr-xr-x. 1 elmeruser elmeruser  28K Sep 26 20:44 ElmerSolver_mpi
-rwxr-xr-x. 1 elmeruser elmeruser  28K Sep 26 20:42 matc
-rwxr-xr-x. 1 elmeruser elmeruser 4.2M Sep 26 20:42 Mesh2D
-rwxr-xr-x. 1 elmeruser elmeruser 455K Sep 26 20:44 Radiators
-rwxr-xr-x. 1 elmeruser elmeruser 505K Sep 26 20:44 ViewFactors
[elmeruser@fedora bin]$ ElmerGUI
bash: ElmerGUI: command not found...
```

**Comment by greyltc** [comment]
@tzwinger, looks like your initials on the readme there

**Comment by tzwinger** [comment]
We had to make a quick new VM based on Fedora, which - as you correctly pointed out - does not contain ElmerGUI. I intend to make a new version based on Ubuntu 22 LTS including ElmerGUI, but if you need a quick fix, you can go to https://www.nic.funet.fi/pub/sci/physics/elmer/bin/VirtualMachines/old/ and download the Elmer 20 LTS version that should contain it. And on a side-note: This is a VM we just maintain for training and education purpose - nothing like an official VM

**Comment by greyltc** [comment]
Just wanted to make sure you're aware!

I was trying to troubleshoot an issue that I was worried was brought on by my local compilation/environment/dependencies. Using a complete, prebuilt (and hopefully tested) environment like a VM seemed perfect for testing this. I did end up going back to the previous ubuntu image like you suggested, but unfortunately the stuff in there was so old that a bunch of the syntax of my input files I wanted to test was too new.

**Comment by tzwinger** [comment]
New Ubuntu 22.04 (LTS) based virtual appliance is downloadable under  https://www.nic.funet.fi/pub/sci/physics/elmer/bin/VirtualMachines/ and it includes ElmerGUI - like always, appliance is provided "as is" - no warranties are taken by me or CSC
