### ISSUE TITLE
VtuOutputSolver.F90 change DGIndexes

### ISSUE THREAD

**Issue by fgillet** [ElmerCSC/elmerfem#442]
setting "Discontinuous Galerkin = Logical True" in the vtu output solver change the solution; see e.g. the elmerice test elmerice/Tests/DGsolver/density.sif comment/uncomment the vtu output file.

Tracking what's happening, VtuOutputSolver calls  CheckAndCreateDGIndexes in MainUtils; and as I understand this routine overwrite the previously existing DGIndexes (created by  CreateDGPerm in MainUtils during initialisation).

DGIndexes in CheckAndCreateDGIndexes should be updated only if not previously existing?
I think this was the intetion with the boolean Failed; but it is never used in the second part of the routine.

**Comment by raback** [comment]
Thanx Fabien for the report. This was fixed already in May, I close the ticket now.
