### ISSUE TITLE
Metric units Helmholtz Equation for noise modelling

### ISSUE THREAD

**Issue by IsotoCedex** [ElmerCSC/elmerfem#455]
Hi all!

First of all, thank you so much for the fantastic tool that you have provided us with Elmer FEM.

I have been checking the usefulness of Elmer's Helmholtz module for the study of acoustic screens in the open field.

I encounter a difficulty that, after many attempts, I cannot solve.

This has to do with the size of the computing domain. I have worked in meters, but the results are not as I expected, since the attenuation of the wave occurs too close to the source.

![image](https://github.com/ElmerCSC/elmerfem/assets/87642224/5603dd05-eee9-43cd-a812-95937e49cf5e)

After checking the tutorials, I have changed the size of the domain, applying the parameter "Coordinate Scaling=0.001), and I find more consistent results, but I don't understand the reason.

![image](https://github.com/ElmerCSC/elmerfem/assets/87642224/3ce1382e-1055-4210-8767-eee5c2ff4329)

In example 17 of Elmer's tutorial manual (https://www.nic.funet.fi/pub/sci/physics/elmer/doc/ElmerTutorials.pdf), why are the spatial units so small? Are they in meters?

![image](https://github.com/ElmerCSC/elmerfem/assets/87642224/899d9fe5-e61f-4503-b007-818c59af11e4)

If you could clarify this for me I would be very grateful.

Here you can find my files: [NoiseBarrier.zip](https://github.com/ElmerCSC/elmerfem/files/14547152/NoiseBarrier.zip)

Greetings

**Comment by richb2k** [comment]
Hello,

Asking this kind of question in the Elmer Forum would probably get more of a response.  

[http://www.elmerfem.org/forum/](url)

You attached a working example, which is probably the best step toward getting help with Elmer, so compliments for that step.

If you search the forum for 'SI units', then several previous posts will come up, such as this post:

[http://www.elmerfem.org/forum/viewtopic.php?p=29214#p29214](url)

Likewise, if you search the Elmer manuals and the GetStartedElmer pdf for 'SI units', then you will find entries like this:

> Q: What unit system should I use in Elmer?
A: Elmer does not assume any specific units so you can use any unit system that is consistent. The natural
choice is SI units. By default the equations are scaled to an optimal range so usually there is no need for
altering the unit system for the sake of numerical accuracy. However, if you choose, for example, your mesh
to be in millimeters remember that it reflects to the units of velocity, density, force, viscosity etc., as well.

One last comment about SI units.  ElmerGUI provides a Material Library.  The material properties are defined using SI units, so using compatible units (meters) for the geometry is the logical choice.

**Comment by IsotoCedex** [comment]
Hello @richb2k ,

Thank you very much for your answer. It has been a great help to me.

I was making a discretization error, since the mesh size was not appropriate for the modeling.

I have applied the following relationship, and it now gives more logical results, although it will need to be refined:

Mesh size = 1/10 wavelength

![image](https://github.com/ElmerCSC/elmerfem/assets/87642224/b8eb2e6b-cd45-45c3-a32b-1f98715134ee)

Next time I will also do the consultation on the forum, which I have seen has a lot of information.

Thanks again.
