### ISSUE TITLE
Allow random Body/Material/BoundaryCondition/Equation/Solver block index in the input script

### ISSUE THREAD

**Issue by lcheng9** [ElmerCSC/elmerfem#458]
The solver complains when these block index is not 1-based incremental, as shown the output message below.
Supporting random block index (but unique) makes Elmer more flexible and compatible to other preprocessors. 
A test case is attached. Thanks.

[elmer_welsim.sif.txt](https://github.com/ElmerCSC/elmerfem/files/14744285/elmer_welsim.sif.txt)
[mesh.boundary.txt](https://github.com/ElmerCSC/elmerfem/files/14744287/mesh.boundary.txt)
[mesh.elements.txt](https://github.com/ElmerCSC/elmerfem/files/14744288/mesh.elements.txt)
[mesh.header.txt](https://github.com/ElmerCSC/elmerfem/files/14744289/mesh.header.txt)
[mesh.nodes.txt](https://github.com/ElmerCSC/elmerfem/files/14744290/mesh.nodes.txt)

```
ELMER SOLVER (v 9.0) STARTED AT: 2024/03/25 09:16:57
ParCommInit:  Initialize #PEs:            1
MAIN: 
MAIN: =============================================================
MAIN: ElmerSolver finite element software, Welcome!
MAIN: This program is free software licensed under (L)GPL
MAIN: Copyright 1st April 1995 - , CSC - IT Center for Science Ltd.
MAIN: Webpage http://www.csc.fi/elmer, Email elmeradm@csc.fi
MAIN: Version: 9.0 (Rev: Release, Compiled: 2024-03-20)
MAIN:  Running one task without MPI parallelization.
MAIN:  Running with just one thread per task.
MAIN:  Lua interpreter linked in.
MAIN:  External optimization routines linked in.
MAIN: =============================================================
MAIN: 
MAIN: 
MAIN: -------------------------------------
MAIN: Reading Model: elmer_welsim.sif
 Caught LUA error:...0-Release/share/elmersolver/lua-scripts/defaults.lua:58: r
LoadInputFile: Scanning input file: elmer_welsim.sif
LoadInputFile: Scanning only size info
LoadInputFile: First time visiting
LoadInputFile: Reading base load of sif file
LoadInputFile: Loading input file: elmer_welsim.sif
LoadInputFile: Reading base load of sif file
LoadInputFile: Number of BCs: 17
WARNING:: LoadInputFile: Entry missing for: Boundary Condition 1
WARNING:: LoadInputFile: Entry missing for: Boundary Condition 2
WARNING:: LoadInputFile: Entry missing for: Boundary Condition 3
WARNING:: LoadInputFile: Entry missing for: Boundary Condition 4
WARNING:: LoadInputFile: Entry missing for: Boundary Condition 5
WARNING:: LoadInputFile: Entry missing for: Boundary Condition 6
WARNING:: LoadInputFile: Entry missing for: Boundary Condition 7
WARNING:: LoadInputFile: Entry missing for: Boundary Condition 8
WARNING:: LoadInputFile: Entry missing for: Boundary Condition 9
WARNING:: LoadInputFile: Entry missing for: Boundary Condition 10
WARNING:: LoadInputFile: Entry missing for: Boundary Condition 11
WARNING:: LoadInputFile: Entry missing for: Boundary Condition 13
WARNING:: LoadInputFile: Entry missing for: Boundary Condition 14
WARNING:: LoadInputFile: Entry missing for: Boundary Condition 15
WARNING:: LoadInputFile: Entry missing for: Boundary Condition 16
LoadInputFile: Number of Body Forces: 0
LoadInputFile: Number of Initial Conditions: 0
LoadInputFile: Number of Materials: 2
WARNING:: LoadInputFile: Entry missing for: Material 1
LoadInputFile: Number of Equations: 1
LoadInputFile: Number of Solvers: 1
LoadInputFile: Number of Bodies: 11
ERROR:: LoadInputFile: Entry missing for: Body 1
```

**Comment by raback** [comment]
There are pros and cons. Oftentimes it is helpful that continuous numbering is requested, sometimes not. We could add some flag to suppress the checking. Even now the missing entries result only to Warn except for bodies where Fatal is used. Even now there are ways to avoid this problem:

1) Use "Target Bodies(1) = 11" in your case.
2) In ElmerGrid use -autoclean which renumbers stuff from 1. 
3) Set "Use Mesh Names = True" and let the "Name" of the entity define the body index. 
4) Use no numbering in sif file and let Elmer do continuous numbering for you. 

But of course additional flexibility may be useful sometimes.

**Comment by lcheng9** [comment]
Hi @raback, Thank you so much for the speedy and details response. 
These methods worked well, particularly the "target body" method can address my concerns and is easy to implement.
