### ISSUE TITLE
Random crashes while repeatedly running the same script

### ISSUE THREAD

**Issue by robtovey** [ElmerCSC/elmerfem#465]
I've recently been playing with a particular mechanical simulation problem and found a surprisingly broad spectrum of behaviours. I've run the attached example 8 times this morning and had:
- 5 successful executions
- two overflow/underflow errors with the message "Norm of solution appears to be NaN"
- one degenerate mesh error which prints the line "ERROR:: ElementMetric: Degenerate 1D element: ..." a LOT of times. The script prints over 2.9e6 lines to stdout!

The command line printouts are attached as log files.
One of the weirdest things to me is that the numerical tracking data is completely deterministic. If I compare the logs of two successful outputs, then the convergence metrics are identical with no rounding errors. But whether the solver crashes or not and which error message I get is completely random.

This doesn't occur on all installations of elmer:
- on 2 ubuntu ppa installs with MUMPS, HYPRE, and MPI linked in I see a roughly 30%-40% crash rate
- on 1 ubuntu ppa install with only MUMPS and MPI linked there are no crashes running the script
- on 1 self-built install (version a399e88) without MUMPS, HYPRE, or MPI linked there are no crashes running the script

I haven't done too much digging but at least from the header printed at the beginning of every `ElmerSolver` call these seem to be the only differences in setup. It looks like HYPRE is the distinguishing factor, but I don't think the script is actually using it. I've used the default umfpack solver without any preconditioners.

Happy to do some debugging on my end if there are any suggestions for how to narrow down the source of the problem, but I don't know how to go much further beyond pointing the finger at HYPRE.

I've attached [the script](https://github.com/ElmerCSC/elmerfem/files/15060402/case.sif.txt) and [mesh](https://github.com/ElmerCSC/elmerfem/files/15060392/mesh.zip) for reproducibility and the log files recording output from `ElmerSolver` in the three/four scenarios:
- [correct.log](https://github.com/ElmerCSC/elmerfem/files/15060411/correct.log)
- [Nan_overflow.log](https://github.com/ElmerCSC/elmerfem/files/15060414/Nan_overflow.log)
- [Nan_underflow.log](https://github.com/ElmerCSC/elmerfem/files/15060416/Nan_underflow.log)
- [degenerate_mesh_abridged.log](https://github.com/ElmerCSC/elmerfem/files/15060443/degenerate_mesh_abridged.log)
(the full version has over 2.9 million lines and is 188MB)

**Comment by robtovey** [comment]
Note this is a cross-posting from [the forum](https://www.elmerfem.org/forum/viewtopic.php?p=30348)

**Comment by juharu** [comment]
Hi 

Thanks for the report. 

The symptoms are typical when, for example, 

a) running multithreaded while some part of the code is not really ready (not re-entrant) 
you could check the output header for something like: 

MAIN: Running in parallel with 2 threads per task. 

b) there is some uninitialized variable in the code (initialized with some random data from memory). 
I can try using "valgrind" on you case, let's see what it gives. 

Br, Juha 

From: "Rob Tovey" ***@***.***> 
To: "ElmerCSC" ***@***.***> 
Cc: "Subscribed" ***@***.***> 
Sent: Monday, 22 April, 2024 12:14:59 
Subject: [ElmerCSC/elmerfem] Random crashes while repeatedly running the same script (Issue #465) 





I've recently been playing with a particular mechanical simulation problem and found a surprisingly broad spectrum of behaviours. I've run the attached example 8 times this morning and had: 

    * 5 successful executions 
    * two overflow/underflow errors with the message "Norm of solution appears to be NaN" 
    * one degenerate mesh error which prints the line "ERROR:: ElementMetric: Degenerate 1D element: ..." a LOT of times. The script prints over 2.9e6 lines to stdout! 


The command line printouts are attached as log files. 
One of the weirdest things to me is that the numerical tracking data is completely deterministic. If I compare the logs of two successful outputs, then the convergence metrics are identical with no rounding errors. But whether the solver crashes or not and which error message I get is completely random. 

This doesn't occur on all installations of elmer: 

    * on 2 ubuntu ppa installs with MUMPS, HYPRE, and MPI linked in I see a roughly 30%-40% crash rate 
    * on 1 ubuntu ppa install with only MUMPS and MPI linked there are no crashes running the script 
    * on 1 self-built install (version [ https://github.com/ElmerCSC/elmerfem/commit/a399e88833ccff4ac3f01fda77607cf1d6c0dce3 | a399e88 ] ) without MUMPS, HYPRE, or MPI linked there are no crashes running the script 


I haven't done too much digging but at least from the header printed at the beginning of every ElmerSolver call these seem to be the only differences in setup. It looks like HYPRE is the distinguishing factor, but I don't think the script is actually using it. I've used the default umfpack solver without any preconditioners. 

Happy to do some debugging on my end if there are any suggestions for how to narrow down the source of the problem, but I don't know how to go much further beyond pointing the finger at HYPRE. 

I've attached [ https://github.com/ElmerCSC/elmerfem/files/15060402/case.sif.txt | the script ] and [ https://github.com/ElmerCSC/elmerfem/files/15060392/mesh.zip | mesh ] for reproducibility and the log files recording output from ElmerSolver in the three/four scenarios: 

    * [ https://github.com/ElmerCSC/elmerfem/files/15060411/correct.log | correct.log ] 
    * [ https://github.com/ElmerCSC/elmerfem/files/15060414/Nan_overflow.log | Nan_overflow.log ] 
    * [ https://github.com/ElmerCSC/elmerfem/files/15060416/Nan_underflow.log | Nan_underflow.log ] 
    * [ https://github.com/ElmerCSC/elmerfem/files/15060443/degenerate_mesh_abridged.log | degenerate_mesh_abridged.log ] (the full version has over 2.9 million lines and is 188MB)

**Comment by juharu** [comment]
Valgrind seems to report several problems in differents parts of the code. I'll investigate, and get back to you. 
Maybe tomorrow.

**Comment by robtovey** [comment]
Thank you for your response.

a. yes, I'm running with `OMP_NUM_THREADS=1` so single threaded and the output header says 

```
MAIN:  Running one task without MPI parallelization.
MAIN:  Running with just one thread per task.
```

b. oh dear, yes, valgrind is a bit rude about what's going on! 😆 
```
==579153== More than 10000000 total errors detected.  I'm not reporting any more.
==579153== Final error counts will be inaccurate.  Go fix your program!
```

Thank you for having a look into it

**Comment by juharu** [comment]
Hi 

There is now a small fix for unitilized variable usage in elmerfem github "devel". Hope this fixes 
your troubles! 

t: Juha

**Comment by robtovey** [comment]
Thank you Juha for fixing this bug.

For future reference, the fix is [fa05cac](https://github.com/ElmerCSC/elmerfem/commit/fa05cacb836366f8b4322ad239bba42aaadf0f84).

I'm a bit uncertain about whether it fixes the behaviour because to test it would require building from source. I'm not sure how the ppa version is built but I have access to a self-built version of a399e88 which does not crash in the way I described above. If I look at the [diff](https://github.com/ElmerCSC/elmerfem/compare/a399e88..fa05cac) between these two versions then the bug you've just fixed is also in a399e88.

If you can tell me how [this version](https://launchpad.net/~elmer-csc-ubuntu/+archive/ubuntu/elmer-csc-ppa) is built then I can verify it on devel?

**Comment by juharu** [comment]
>bug you've just fixed is also in [ https://github.com/ElmerCSC/elmerfem/commit/a399e88833ccff4ac3f01fda77607cf1d6c0dce3 | a399e88 ] 
Yes, how it behaves can depend on a lot of things. Any small changes in environment, 
compilation, linking, etc. etc. might change the behaviour... I'm not very surprised that 
different executables behave differently. 




>If you can tell me how [ https://launchpad.net/~elmer-csc-ubuntu/+archive/ubuntu/elmer-csc-ppa | this version ] is built then I can verify it on devel? I have no idea, anyone ?

**Comment by robtovey** [comment]
I have just tried the latest ppa update (the filename includes the commit number so I recognised that today's build included your bug fix!) and it looks like everything is working now. 

I have just run the script 75 times without any crashes so that's good enough for me!

Thank you again for such a quick bug fix.

**Comment by juharu** [comment]
Nice and thanks again for reporting!
