### ISSUE TITLE
elmerPost seems uncompilable on Mac OSX Monterey

### ISSUE THREAD

**Issue by ghostforest** [ElmerCSC/elmerfem#476]
elmerPost seems to call functions like:

elm_6node_triangle_isoline
elm_4node_tetra_isosurface
elm_4node_tetra_point_inside

These functions just dont seem to exist. Anywhere.

my compiler is asking me, did u mean:
elm_10node_tetra_triangulate
elm_10node_tetra_isosurface
elm_10node_tetra_isoline

**Comment by raback** [comment]
ElmerPost is obsolite. No need to compile it. It is kept currently for few old-time users. New users should rather use Paraview.
