### ISSUE TITLE
Compilation errors with BOZ literal constants in mpif.h

### ISSUE THREAD

**Issue by Foadsf** [ElmerCSC/elmerfem#482]
## Description

Following [this](https://github.com/ElmerCSC/elmerfem/issues/479) failed attempt, and [this](https://stackoverflow.com/q/78740605/4999991) SO post, when attempting to build Elmer using `cmake --build .`, I'm encountering multiple compilation errors related to BOZ (Binary, Octal, or Hexadecimal) literal constants in the `mpif.h` file. The errors suggest that these constants are being used in a way that's not compatible with the current compiler settings.

```bash
git clone https://github.com/ElmerCSC/elmerfem
git checkout 8bff09ddc7a0da78b6ba17b19a9afebe2c7824d7
cd elmerfem
mkdir build
cd build
```

running three times:

```bash
cmake -DMPI_C_LIBRARIES=/mingw64/lib/libmsmpi.dll.a -DMPI_CXX_LIBRARIES=/mingw64/lib/libmsmpi.dll.a -DMPI_Fortran_LIBRARIES=/mingw64/lib/libmsmpi.dll.a ..
```

and then

```bash
cmake --build .
```

## Error Messages
The compilation fails with the following error messages (truncated for brevity):

```
[1041/2507] Building Fortran object mathlibs/src/parpack/CMakeFiles/parpack.dir/pdlamch.f.obj
FAILED: mathlibs/src/parpack/CMakeFiles/parpack.dir/pdlamch.f.obj
C:\tools\msys64\mingw64\bin\gfortran.exe -IC:\dev\Elmer\20240712\elmerfem\mathlibs\src\parpack -IC:/tools/msys64/mingw64/include -fallow-argument-mismatch -O2 -g -Jfmodules -fpreprocessed -c mathlibs/src/parpack/CMakeFiles/parpack.dir/pdlamch.f-pp.f -o mathlibs/src/parpack/CMakeFiles/parpack.dir/pdlamch.f.obj
mpif.h:227:36:

Error: BOZ literal constant at (1) is neither a data-stmt-constant nor an actual argument to INT, REAL, DBLE, or CMPLX intrinsic function [see '-fno-allow-invalid-boz']
mpif.h:303:27:

Error: BOZ literal constant at (1) is neither a data-stmt-constant nor an actual argument to INT, REAL, DBLE, or CMPLX intrinsic function [see '-fno-allow-invalid-boz']

... (multiple similar errors omitted for brevity)

mpif.h:400:28:

Error: BOZ literal constant at (1) is neither a data-stmt-constant nor an actual argument to INT, REAL, DBLE, or CMPLX intrinsic function [see '-fno-allow-invalid-boz']
[1049/2507] Generating Fortran dyndep file fem/src/CMakeFiles/elmersolver.dir/Fortran.dd
ninja: build stopped: subcommand failed.
```

## Environment
- OS: Windows (using MSYS2 MinGW64)
- Compiler: GFortran 14.1.0
- CMake version: 3.30.0
- Elmer version or commit hash: `8bff09ddc7a0da78b6ba17b19a9afebe2c7824d7`

## Possible Solution
The error messages suggest using the `-fno-allow-invalid-boz` compiler flag. However, this might be a workaround rather than a proper fix. The root cause seems to be in how the BOZ literals are used in `mpif.h`, which might need to be updated for compatibility with newer Fortran standards or compiler versions.

## Questions
1. Is this a known issue with the current version of Elmer?
2. Are there any plans to update the `mpif.h` file to address these BOZ literal constant issues?
3. Is there a recommended workaround or fix for users encountering this problem?

Any assistance or guidance on resolving these compilation errors would be greatly appreciated. Thank you!

**Comment by mmuetzel** [comment]
Afaict, `mpif.h` is not part of ElmerFEM and ElmerFEM has no control over its content (unless MPI is disabled and ElmerFEM substitutes a stub header - which doesn't seem to be the case for you).

Looking at your configuration command, I'm guessing that you are using the import libraries and headers that MSYS2 distributes. (Note that MSYS2 doesn't distribute the actual implementation of MSMPI. You'll need to get that from Microsoft directly.)
If one of the headers that the MSYS2 project distributes causes compilation errors for you, it might be best to report that to them:
https://github.com/msys2/MINGW-packages/issues

**Comment by mmuetzel** [comment]
I opened https://github.com/msys2/MINGW-packages/pull/21404 for upstream MSYS2 that should hopefully address this issue.

**Comment by mmuetzel** [comment]
@Foadsf: Could you please test whether the build artifact from that PR resolves the issue for you?
You can download the build artifacts from the "Artifacts" pulldown on the "Checks" tab: https://github.com/msys2/MINGW-packages/pull/21404/checks
After unpacking the build artifact, you could install it, e.g., with `pacman -U mingw-w64-*-msmpi-*`.

**Comment by mmuetzel** [comment]
This is not a bug in ElmerFEM. The issue has been solved by an update of the header that is distributed by MSYS2.

This issue can be closed now.

**Comment by Foadsf** [comment]
@mmuetzel thanks for the kind support and follow-up on this issue. I removed the `bug` label as you correctly pointed out, it was an MSYS2 issue. So I believe I can update the [`feat/windows-msys2-build`](https://github.com/ElmerCSC/elmerfem/tree/feat/windows-msys2-build) branch with `-DWITH_MPI=ON`, right?

**Comment by mmuetzel** [comment]
> So I believe I can update the feat/windows-msys2-build branch with -DWITH_MPI=ON, right?

You could do that. But like I wrote several times before: You'd need to install MSMPI from Microsoft on the runner or the test suite won't work.

**Comment by mmuetzel** [comment]
To be clear: I'd recommend to *not* build with MPI on GitHub-hosted Windows runners (unless you figure out how to install MSMPI on them).

**Comment by mmuetzel** [comment]
ElmerFEM builds with MSMPI in CI now. 
I guess this issue could be closed.
