### ISSUE TITLE
SIGSEGV: Segmentation fault

### ISSUE THREAD

**Issue by Mohamed-Dz** [ElmerCSC/elmerfem#49]
Hello,
I'm on Ubuntu 14.04 32bit, I've installed **elmerfem-csc** package as mentioned in: https://www.csc.fi/web/elmer/binaries
ElmerGUI works fine, I can do everything from importing geometry to generating sif file. The problem is when I start the solver I got:

```
ELMER SOLVER (v 8.1) STARTED AT: 2016/01/05 10:37:34
ParCommInit:  Initialize #PEs:            1
MAIN: 
MAIN: =============================================================
MAIN: ElmerSolver finite element software, Welcome!
MAIN: This program is free software licensed under (L)GPL
MAIN: Copyright 1st April 1995 - , CSC - IT Center for Science Ltd.
MAIN: Webpage http://www.csc.fi/elmer, Email elmeradm@csc.fi
MAIN: Version: 8.1, Compiled: 2015-12-30)
MAIN: =============================================================
MAIN: 
MAIN: 
MAIN: -------------------------------------
MAIN: Reading Model: case.sif
Loading user function library: [StressSolve]...[StressSolver_Init0]

Program received signal SIGSEGV: Segmentation fault - invalid memory reference.

Backtrace for this error:
#0  0xB723F163
#1  0xB723F800
#2  0xB77603FF
#3  0x0
Segmentation fault (core dumped)
```

This happens with all the cases I've tested, even the most basic ones.

What's wrong ?

regards.

**Comment by raback** [comment]
Hi, current Elmer version is tested and supported only for 64 bit systems. So my guess that your 32 bit OS could be the problem.

**Comment by Mohamed-Dz** [comment]
Hello,
I don't think th OS is the problem as I'm actually running successfully a lot of other heavy numerical applications.
Thank you.
