### ISSUE TITLE
Build fails due to conflicting ToroidCurrents module definitions

### ISSUE THREAD

**Issue by Foadsf** [ElmerCSC/elmerfem#491]
### Description

Following [this issue](https://github.com/ElmerCSC/elmerfem/issues/489), when building Elmer FEM, the build process fails with the following error:

```
[1913/2375] Generating Fortran dyndep file fem/tests/mgdyn_lamstack_lowfreq_transient/CMakeFiles/mgdyn_lamstack_lowfreq_transient_currents.dir/Fortran.dd
ninja: build stopped: multiple rules generate fmodules/toroidcurrents.mod.
```

This error occurs because there are multiple definitions of the `ToroidCurrents` module in different test directories.

### Files affected

The `ToroidCurrents` module is defined in the following files:

1. `fem/tests/mgdyn_anisotropic_cond/currents.f90`
2. `fem/tests/mgdyn_lamstack_lowfreq_transient/currents.f90`

### Steps to reproduce

1. Clone the Elmer FEM repository

    ```bash
    git clone https://github.com/ElmerCSC/elmerfem
    cd elmerfem
    git checkout adafcd2b7fcc4c5f804d2fcd2e9de0ba4350f630
    ```
2. Create a build directory and configure the build:
    ```bash
    mkdir build
    cd build
    cmake -D WITH_MPI=OFF ..
    ```
3. Build the project:
    ```bash
    cmake --build .
    ```

### Expected behavior

The build should complete successfully, properly handling the multiple definitions of the `ToroidCurrents` module.

### Actual behavior

The build fails due to conflicting rules for generating `fmodules/toroidcurrents.mod`.

### Possible solutions

1. Rename one of the `ToroidCurrents` modules to avoid the conflict.
2. Modify the CMake configuration to handle multiple definitions of the same module across different test directories.
3. Consolidate the `ToroidCurrents` module into a shared location that can be used by multiple tests.

### Additional information

This issue may be related to how Fortran modules are handled in the CMake build system, particularly for test cases that may have similar or identical module definitions.

**Comment by mmuetzel** [comment]
I can confirm this issue with the Ninja generator (where it is probably not platform dependent and would also happen on Linux or other platforms).

To work around the issue, you could switch to a Makefiles generator. E.g.:
```
cmake -G"MSYS Makefiles" -DWITH_MPI=OFF --fresh ..
cmake --build . -j8
```

It would still be nice if this issue would be fixed so the tests could be built with any generator.

**Comment by Foadsf** [comment]
I just tried the latest commit `77bbe42cd96e213af77e4e83453db905e2232f8f` and it still throws the error:

```
[1912/2375] Generating Fortran dyndep file fem/tests/mgdyn_lamstack_lowfreq_transient/CMakeFiles/mgdyn_lamstack_lowfreq_transient_currents.dir/Fortran.dd
ninja: build stopped: multiple rules generate fmodules/toroidcurrents.mod.
```

However, disabling Nijna and building for GNU Make without parallelism with ([reerence](https://www.msys2.org/docs/cmake/)):

```bash
cmake -D WITH_MPI=OFF -G "MinGW Makefiles" ..
mingw32-make
```

succeeds!

**P.S.** I asked a follow-up question [here](https://discord.com/channels/792780131906617355/1260936217948590112/1262664280411607133) on Discord.

**Comment by mmuetzel** [comment]
`MinGW Makefiles` behave a bit oddly sometimes. I'd recommend using the `MSYS Makefiles` generator (followed by building with `make` or `cmake --build .` which works with any generator).

**Comment by Foadsf** [comment]
Following [this](https://discord.com/channels/792780131906617355/1260936217948590112/1262666236542844958) message on Discord, the building suceeds with:

```bash
cmake -D WITH_MPI=OFF -G "MSYS Makefiles" ..
mingw32-make
```

though it took a long long time to finish. So this is either an issue with parallelism or Ninja.

**Comment by mmuetzel** [comment]
You should *not* try and build from `MSYS Makefiles` with `mingw32-make`. I'd really advice you to use `cmake --build .`. Especially, if you are unsure which the correct build tools are.
Also, there is no Ninja in the mix anymore. So, I don't understand what you mean with the last sentence.

To build with multiple parallel processes, you could use, e.g., `cmake --build . -j8`.

**Comment by Foadsf** [comment]
building with

```bash
cmake -D WITH_MPI=OFF -G "MSYS Makefiles" ..
cmake --build .
```

succeeds, and it seems to be even faster than `mingw32-make`! 🤔

@mmuetzel you are right. Ninja doesn't seem to have anything with the error, but it is an issue with parallelism.

**Comment by mmuetzel** [comment]
`MSYS Makefiles` means you *need* to use `make` as the build tool. `MinGW Makefiles` would mean that you would *need* to use `mingw32-make` as the build tool. Never mix the two.
Mixing the two might not immediately result in build errors. But you are definitely in undefined behavior terrain if you do that. So, never mix them! (Not sure why you are continuing to even mention it...)

Instead as a rule of thumb: *Always* invoke CMake with `cmake --build` (plus potential command line flags) for the build step!
