### ISSUE TITLE
Can't install Elmer-FEM on Ubuntu 16.04 LTS from PPA

### ISSUE THREAD

**Issue by ghost** [ElmerCSC/elmerfem#54]
Can't install Elmer-FEM on Ubuntu 16.04 LTS from PPA

**Comment by juhanikataja** [comment]
Thanks! It seems that in Ubuntu 16.04 libqt4-gui packages was renamed to libqtgui4. Should be fixed now.

**Comment by ghost** [comment]
You welcome!
Please, solve the problems with the following software packages:
- libmumps-4.10.0
- libhypre-2.8.0b
- liboce-foundation8
- iboce-modeling8
- libvtk5.10
- libqwt6
- libvtk5.10-qt4

It seems that in Ubuntu 16.04 every items in the previous list of packages was changed their versions or names.

**Comment by ghost** [comment]
**Thank you! Now it works!**
