### ISSUE TITLE
SALOME with Elmer-FEM

### ISSUE THREAD

**Issue by ghost** [ElmerCSC/elmerfem#55]
I have a problem with opening *.unv mesh-files in Elmer-FEM. Mesh-files are generated in SALOME.
After file loading I see one base line at the space in Elmer-GUI and messages (in console) about “unknown data types in *.unv file”

**Comment by crobarcro** [comment]
I had this problem too, but what you really need to do is convert to elmer's mesh format first using the ElmerGrid program, see an example of doing this in this forum thread: http://www.elmerfem.org/forum/viewtopic.php?f=16&t=4028

**Comment by raback** [comment]
The UNV reading capabilities have been updated. They may still be lacking but new non-working UNV files are needed in that case. I close this for now.
