### ISSUE TITLE
Parallel make does not work on Mac OS X

### ISSUE THREAD

**Issue by dingzeyuli** [ElmerCSC/elmerfem#57]
On Mac OS X, El Capitan, "make" would work. But "make -j4" failed.

**Comment by jvela018** [comment]
It works on BigSur 11.0.1. I cannot check earlier versions but you can find the use of make -j4 around min 12:07 of the MacOS installation video https://www.youtube.com/watch?v=rQhSYKHw3HM .

**Comment by Foadsf** [comment]
@jvela018  Once I wrote a small CMake script that would find the number of cores available and then run `make -j<N>` where `N` is the number of cores available minuse one. I think we can implment this for Elmer as well, to make sure parallel computing is default behaviour for compiling.

**Comment by Foadsf** [comment]
an example from [here](https://cmake.org/cmake/help/latest/module/ProcessorCount.html):

~~~cmake
include(ProcessorCount)
ProcessorCount(N)
MATH(EXPR N "${N}-1")
if(NOT N EQUAL 0)
  set(CMAKE_MAKE_PROGRAM "${CMAKE_MAKE_PROGRAM} -j ${N}")
endif()
~~~

and then build with `cmake --build `

**Comment by mmuetzel** [comment]
It's been more than 8 years since this was originally reported. Is this still an issue?

**Comment by jvela018** [comment]
@mmuetzel @Foadsf , I haven't really been doing anything related to Elmer in a while, but I think this has nothing to do with Elmer itself and more with the MacOS operating system. Have you tried building it like this?

make -j$(sysctl -n hw.ncpu)

This would be the analogous way of doing make -j$(nproc) in Linux.

BR,

/Jon

**Comment by mmuetzel** [comment]
If I understood the original reporter correctly, they were able to build with `make` but not with `make -j4`. I don't see how `make -j$(sysctl -n hw.ncpu)` would behave much differently from the latter.
Am I missing something?

**Comment by jvela018** [comment]
@mmuetzel 

Are you having this issue? I am able to build Elmer 3 ways, using 

`make -j4`

`make -j$(sysctl -n hw.ncpu)`

`make -j $(getconf _NPROCESSORS_ONLN)`


@dingzeyuli . Is this still an issue or can we close this issue? 

I would suggest the last two, as you can use as many processors as available/needed.

Thanks. /Jon

**Comment by mmuetzel** [comment]
I don't have that issue either. That's why I asked whether this is still an issue (for some).

**Comment by jvela018** [comment]
@dingzeyuli ,

I'll proceed to close this issue.

Feel free to reopen issue if this is still an issue to you, and provide us with the steps to replicate this issue?


Thanks,

/Jon
