### ISSUE TITLE
ElmerGUI should not offer sif file edit, or should have option to use user sif file

### ISSUE THREAD

**Issue by crobarcro** [ElmerCSC/elmerfem#58]
ElmerGUI has the option to edit the .sif file manually/ However, ElmerGUI overwrites the changes on exit with the current GUI menu selections. This is not a good situation. Either it should not be possible to edit the sif file in ElmerGUI (and all mention of it stripped from ElmerGUI so users are not tempted to edit it manually), or an option to use a user created .sif file added to the GUI so the menu options are then ignored for this project. This setting could be stored in the xml file which currently stores the 'real' settings that are used for the project.

At the moment, using a hand crafted .sif file with ElmerGUI is practically impossible. See further discussion of this on the forum thread here:

http://www.elmerfem.org/forum/viewtopic.php?f=4&t=605&start=10&sid=25042abba18143a2757343c03d4c062f

**Comment by raback** [comment]
These issues have been significantly improved by the great work of t7saeki. The pertaining issue is to have them available in Windows installers. For lauchpad the nightly builds should already offer these.
