### ISSUE TITLE
Binary Gmsh files

### ISSUE THREAD

**Issue by petsuter** [ElmerCSC/elmerfem#603]
[Gmsh version 2 legacy files](https://gmsh.info/doc/texinfo/gmsh.html#MSH-file-format-version-2-_0028Legacy_0029) can be binary or text files. For text files the `$MeshFormat version-number file-type data-size` has `file-type` as `0`. Python libraries like [meshio](https://github.com/nschloe/meshio/blob/main/src/meshio/gmsh/_gmsh22.py) default to binary and write `file-type` as `1`. (The text format can be requested with `binary=False`.)

I think ElmerGrid only supports the text variant of the Gmsh 2 file format, right? Perhaps a check/warning in [egconvert.c](https://github.com/ElmerCSC/elmerfem/blob/devel/elmergrid/src/egconvert.c#L4072) could be added? (At least I ran into confusing errors with a binary Gmsh 2 file and switching to text fixed it.)

Thanks.

**Comment by richb2k** [comment]
A check for a gmsh binary input file has been added.  Please test a recent (1 Nov 2024 or newer) build and let us know if it works for you.

**Comment by petsuter** [comment]
I tested it and it works, thanks!

Now with the new message it's much clearer:
```
Elmergrid loading data:
-----------------------
Format chosen using the first line: $MeshFormat
Gmsh version is 2.2
Error: Gmsh input file is in binary format! Exiting.
***** ERROR: We cannot continue with this! *****
***** Gmsh input file is in binary format!
***** ...now exiting to system!
```

Just for comparison here is the old output with the same file:

```
Elmergrid loading data:
-----------------------
Format chosen using the first line: $MeshFormat
Gmsh version is 2.2
Loading mesh in Gmsh format 2.0 from file example.msh
$MeshFormat section should end to string $EndMeshFormat:

$Nodes section should end to string $EndNodes:

Allocating for 36896 knots and 0 elements.
Allocation impossible in imatrix: 1 0 0 -1
```
