### ISSUE TITLE
Joule Heating in MagnetoDynamicsCalcFields requires imaginary component and averaging

### ISSUE THREAD

**Issue by jvencels** [ElmerCSC/elmerfem#67]
In the file **fem/src/modules/MagnetoDynamics.F90** the comment on lines **6490-6492** says:

> ! Now Power = J.conjugate(E), with the possible imaginary component neglected.
> ! Perhaps we should set Power = 1/2 J.conjugate(E) so that the average power
> ! would be obtained.

Could you please include imaginary component and compute the average power?
[case.txt](https://github.com/ElmerCSC/elmerfem/files/483170/case.txt)

**Comment by juhanikataja** [comment]
[This](https://github.com/ElmerCSC/elmerfem/commit/9c2f8262f0ac8e7e6cf037d9c4c8f9ecb1b2d1dd) commit fixes the 1/2 part. Still only real part of the power is calculated.
