### ISSUE TITLE
vtk 6 compatibility

### ISSUE THREAD

**Issue by icefinger** [ElmerCSC/elmerfem#74]
The fact that it is not compilable with gtk 6 makes it impossible to fully compile on debian stretch with the official packages only. Making it compilable with debian stretch would make it compatible with future ubuntus too.

**Comment by juhanikataja** [comment]
Just noting that enabling OCC requires VTK as well.

**Comment by raback** [comment]
This has been recently addressed by Saeki's work on ElmerGUI!
