### ISSUE TITLE
Segmentation fault for complex mesh

### ISSUE THREAD

**Issue by icefinger** [ElmerCSC/elmerfem#76]
Dear developers,
I have a crash trouble during the meshing for a specific case (.step attached) in which you have a very small sphere/tube inside a big sphere. This crash (segmentation fault) disappears for bigger sphere/tube.
How to reproduce: just open the attached file with ElmerGUI.

Attachment: https://rewolf.ge.infn.it/owncloud/public.php?service=files&t=85d9d13c2bcf08934c46393734a62bb5

Thanks for your great work

**Comment by raback** [comment]
Unfortunately built-in ElmerGUI meshing is a very simple one only supporting one body. Meshing in Salome is preferably for complex geometries. When you save the mesh in UNV format you can utilize the entity names. Unfortunately we are not planning to further develop these features in ElmerGUI and hence I will close this even though the bug persists. I hope the Salome GUI will be a complete solution soon.
