### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by randyheydon** [ElmerCSC/elmerfem#8]
According to [this forum post](http://www.elmerfem.org/forum/viewtopic.php?f=11&t=3797), this repository is now the official source repository, replacing the old SVN repository.  Therefore, [the README](https://github.com/ElmerCSC/elmerfem/blob/devel/README.txt) in this repository needs to be updated; it still claims that the previous repository is official, and gives a past date as the expected transition time.  This needs correcting to reflect the current state of Elmer.

**Comment by juhanikataja** [comment]
Thank you! Fixed in eb3664d5abcb6764f7191d79089dc01ab6664d09
