### ISSUE TITLE
call backtrace at DefUtils.F90

### ISSUE THREAD

**Issue by juhanikataja** [ElmerCSC/elmerfem#90]
`CALL BACKTRACE` utilized [here](https://github.com/ElmerCSC/elmerfem/blob/devel/fem/src/DefUtils.F90#L5727) causes linking with Intel Fortran 17.0.1 to fail, it seems that ifort does not support this gnu extension.

**Comment by mbycklin** [comment]
Agreed, BACKTRACE is a GNU extension. Wrapping the code to be GNU Fortran specific would fix the linking issue: 
 `#ifdef __GFORTRAN__`
 `IF(.NOT.PRESENT(Caller)) CALL BACKTRACE`
`#endif`
