### ISSUE TITLE
VtuOutputSolver.F90 GeometryIds variable Bug

### ISSUE THREAD

**Issue by ettaka** [ElmerCSC/elmerfem#97]
@raback A small problem with GeometryIds variable has emerged recently: 
We have tracked the problem to [this](https://github.com/ElmerCSC/elmerfem/blob/devel/fem/src/modules/ResultOutputSolve/VtuOutputSolver.F90#L1581) line. 

Should the condition include j==1?
`IF ( j>=1 .AND. j<= SIZE(GeometryBCMap)) j = GeometryBCMap( j )`

This fixes the problem for us but not sure if it is in order otherwise?

**Comment by juharu** [comment]
Hi, 

seems like a bug (and probably my doing, sorry!), please commit the correction ? 

Juha
